/* Runtime config for the site. Plain committed file — it used to be generated by
   infra/Makefile (`make config`) against Terraform outputs, but the AWS deploy is retired.

   SYNC_URL points at the Cloudflare Worker that replaced the AWS Lambda. If it is empty the
   app runs local-only (default password "123") so the raw files still work when opened
   straight off disk.

   NOTE: login.html copies this value into localStorage as `de.__syncurl`, so a browser keeps
   calling whatever URL it saw when it last logged in. After changing this, log out and back
   in once on each device. */
window.DE_CONFIG = { SYNC_URL: "https://german-sync.mhosnytech.workers.dev" };
