/* German Study — every lesson's Anki deck in one place.
 *
 * AUTO-GENERATED from the lesson files' own window.PAGE blocks. Do not hand-edit:
 * add or change cards in the lesson HTML, then re-run the generator.
 *
 * Why this file exists: a lesson's deck used to live only inside its own page, so
 * the hub had no way to offer "export everything I've finished" without fetching and
 * parsing every lesson. Keyed by the permanent slug, same as lessons.js.
 *   DECKS[slug] = { deck: "<deck name>", cards: [{f, b, ex?}, ...] }
 */
window.DECKS = {
  "alphabet": {
    deck: "DE · Alphabet & Aussprache",
    cards: [
      {"f":"ä (kurz)","b":"sounds like a short English 'e'","ex":"Männer, Hände"},
      {"f":"ü","b":"say 'ee' with rounded lips","ex":"über, Tür, grün"},
      {"f":"ö","b":"say 'e' with rounded lips","ex":"schön, Öl, Köpfe"},
      {"f":"ch (nach e/i)","b":"soft, hissed at front of mouth","ex":"ich, manchmal"},
      {"f":"ch (nach a/o/u)","b":"hard, throaty (back of throat)","ex":"machen, Dach, Loch"},
      {"f":"-ig (Wortende)","b":"pronounced like -ich","ex":"Honig, König"},
      {"f":"ie","b":"one long 'ee'","ex":"liegen, Biene"},
      {"f":"ei","b":"'eye'","ex":"mein, Stein, Weise"},
      {"f":"eu / äu","b":"'oy'","ex":"Zeug, Häuser, Mäuse"},
      {"f":"au","b":"'ow'","ex":"Stau, Mauer, bauen"},
      {"f":"v","b":"like English 'f'","ex":"Vater, vier, Vase"},
      {"f":"w","b":"like English 'v'","ex":"Wasser, Wald"},
      {"f":"z","b":"like 'ts'","ex":"Zebra, Zunge"},
      {"f":"ß","b":"sharp s; makes vowel before it long","ex":"Straße, Fuß, Spaß"},
      {"f":"h nach Vokal","b":"silent — lengthens the vowel","ex":"Sahne, Bahn"},
      {"f":"r am Wortende","b":"barely spoken (vocalised)","ex":"Vater→'Vata', Mutter"},
      {"f":"sch","b":"like English 'sh'","ex":"schön, waschen"},
      {"f":"Doppelkonsonant (nn, ff…)","b":"makes the vowel BEFORE it short","ex":"Kaffee, Sonne"}
    ]
  },
  "tea": {
    deck: "DE · Tee & Küche",
    cards: [
      {"f":"das Wasser (kein Plural)","b":"water"},
      {"f":"der Wasserhahn → die Wasserhähne","b":"the tap / faucet"},
      {"f":"der Wasserkocher → die Wasserkocher","b":"the (electric) kettle"},
      {"f":"der Schalter → die Schalter","b":"the switch","ex":"Der Schalter steht auf an/aus."},
      {"f":"die Tasse → die Tassen","b":"the cup"},
      {"f":"der Henkel → die Henkel","b":"the handle (of a cup)"},
      {"f":"der Tee → die Tees","b":"the tea"},
      {"f":"der Teebeutel → die Teebeutel","b":"the tea bag"},
      {"f":"die Verpackung → die Verpackungen","b":"the packaging"},
      {"f":"die Sorte → die Sorten","b":"the kind / variety","ex":"verschiedene Sorten Tee"},
      {"f":"aufmachen ⇄ zumachen","b":"to open ⇄ to close"},
      {"f":"kochen","b":"to boil / cook","ex":"Das Wasser kocht."},
      {"f":"gießen","b":"to pour","ex":"Wasser in die Tasse gießen"},
      {"f":"ziehen (Tee)","b":"to steep","ex":"Der Tee muss ziehen."},
      {"f":"lose (Tee)","b":"loose (not in a bag)"},
      {"f":"an ⇄ aus","b":"on ⇄ off"},
      {"f":"auf ⇄ zu","b":"open ⇄ closed"}
    ]
  },
  "kitchen": {
    deck: "DE · Die Küche",
    cards: [
      {"f":"die Küche → die Küchen","b":"the kitchen"},
      {"f":"der Schrank → die Schränke","b":"cupboard → cupboards","ex":"Der Schrank steht auf dem Boden."},
      {"f":"der Boden → die Böden","b":"the floor"},
      {"f":"die Wand → die Wände","b":"the wall","ex":"Die Schränke hängen an der Wand."},
      {"f":"die Schublade → die Schubladen","b":"drawer → drawers"},
      {"f":"das Fach → die Fächer","b":"compartment / shelf"},
      {"f":"die Ecke → die Ecken","b":"the corner"},
      {"f":"der Backofen → die Backöfen","b":"the oven","ex":"Im Backofen kann man backen."},
      {"f":"der Herd → die Herde","b":"the stove / cooktop"},
      {"f":"die Herdplatte → die Herdplatten","b":"the hob / burner","ex":"Der Herd hat vier Herdplatten."},
      {"f":"der Topf → die Töpfe","b":"the pot","ex":"Im Topf kann man Suppe kochen."},
      {"f":"die Pfanne → die Pfannen","b":"the pan","ex":"In der Pfanne kann man ein Steak anbraten."},
      {"f":"das Schneidebrett → die Schneidebretter","b":"the cutting board"},
      {"f":"das Messer → die Messer","b":"the knife"},
      {"f":"das Spülbecken → die Spülbecken","b":"the sink"},
      {"f":"der Wasserhahn → die Wasserhähne","b":"the tap / faucet"},
      {"f":"das Radio → die Radios","b":"the radio","ex":"Aus dem Radio kommt Musik."},
      {"f":"das Besteck (kein Plural)","b":"the cutlery (collective)"},
      {"f":"der Löffel → die Löffel","b":"the spoon"},
      {"f":"die Gabel → die Gabeln","b":"the fork"},
      {"f":"der Kochlöffel → die Kochlöffel","b":"the wooden / cooking spoon"},
      {"f":"der Teller → die Teller","b":"the plate"},
      {"f":"der Küchengummi → die Küchengummis","b":"the rubber band"},
      {"f":"die Gewürze (nur Plural)","b":"the spices (Pfeffer & Salz)"},
      {"f":"backen","b":"to bake (im Backofen)"},
      {"f":"anbraten","b":"to fry / sear (in der Pfanne)"},
      {"f":"schneiden","b":"to cut (mit dem Messer)"},
      {"f":"stehen / hängen / liegen","b":"to stand / hang / lie (be positioned)"},
      {"f":"zwischen … und …","b":"between … and …"}
    ]
  },
  "hands": {
    deck: "DE · Hände & Finger",
    cards: [
      {"f":"die Hand → die Hände","b":"hand → hands"},
      {"f":"der Finger → die Finger","b":"finger"},
      {"f":"der Daumen → die Daumen","b":"thumb","ex":"einen Daumen nach oben geben = thumbs up"},
      {"f":"der Zeigefinger → die Zeigefinger","b":"index finger","ex":"Mit dem Zeigefinger kann man zeigen."},
      {"f":"der Mittelfinger → die Mittelfinger","b":"middle finger"},
      {"f":"der Ringfinger → die Ringfinger","b":"ring finger","ex":"Ich trage einen Ring am Ringfinger."},
      {"f":"der kleine Finger → die kleinen Finger","b":"little finger / pinky"},
      {"f":"der Fingernagel → die Fingernägel","b":"fingernail"},
      {"f":"die Faust → die Fäuste","b":"fist → fists"},
      {"f":"links / rechts","b":"left / right"},
      {"f":"zeigen (auf)","b":"to point (at)","ex":"Ich zeige auf den Tisch."},
      {"f":"anfassen","b":"to touch","ex":"Ich fasse den Ring an."},
      {"f":"klatschen","b":"to clap"},
      {"f":"winken","b":"to wave"},
      {"f":"eine Faust machen","b":"to make a fist"}
    ]
  },
  "tram": {
    deck: "DE · Straßenbahn",
    cards: [
      {"f":"die Straßenbahn → die Straßenbahnen","b":"the tram"},
      {"f":"die Haltestelle → die Haltestellen","b":"the stop"},
      {"f":"der Fahrgast → die Fahrgäste","b":"passenger → passengers"},
      {"f":"die Fahrkarte → die Fahrkarten","b":"the ticket"},
      {"f":"der Fahrkartenautomat → die Fahrkartenautomaten","b":"the ticket machine"},
      {"f":"die Anzeigetafel → die Anzeigetafeln","b":"the display board"},
      {"f":"die Ansage → die Ansagen","b":"the announcement","ex":"Nächste Haltestelle…"},
      {"f":"der Sitz → die Sitze","b":"seat → seats"},
      {"f":"die Tür → die Türen","b":"the door"},
      {"f":"der Knopf → die Knöpfe","b":"the button","ex":"Ich drücke den Knopf."},
      {"f":"einsteigen","b":"to get on (separable)","ex":"Ich steige ein."},
      {"f":"aussteigen","b":"to get off (separable)","ex":"Ich steige aus."},
      {"f":"abfahren","b":"to depart (separable)","ex":"Die Bahn fährt ab."},
      {"f":"anhalten","b":"to stop (separable)","ex":"Die Bahn hält an."},
      {"f":"einfahren","b":"to pull in (separable)","ex":"Die Bahn fährt ein."},
      {"f":"kosten","b":"to cost","ex":"Die Fahrkarte kostet 3,40 €."}
    ]
  },
  "cattable": {
    deck: "DE · Katze & Tisch",
    cards: [
      {"f":"die Katze → die Katzen","b":"the cat"},
      {"f":"das Fell (kein Plural)","b":"the fur (of an animal)","ex":"Das Fell der Katze ist weich."},
      {"f":"das Haar → die Haare","b":"hair (people have Haare)"},
      {"f":"die Nase → die Nasen","b":"the nose","ex":"Die Nase der Katze ist rosa."},
      {"f":"die Maus → die Mäuse","b":"mouse → mice","ex":"Die Katze träumt vom Mäusefangen."},
      {"f":"der Tisch → die Tische","b":"the table","ex":"Der Tisch ist rund und aus Metall."},
      {"f":"der Stuhl → die Stühle","b":"the chair"},
      {"f":"der Pinsel → die Pinsel","b":"the (paint)brush","ex":"Der Pinsel ist weich."},
      {"f":"das Handy → die Handys","b":"the mobile phone","ex":"Das Handy ist hart."},
      {"f":"der Fächer → die Fächer","b":"the hand fan"},
      {"f":"weich ⇄ hart","b":"soft ⇄ hard"},
      {"f":"rund ⇄ eckig","b":"round ⇄ angular"},
      {"f":"aus Holz","b":"(made) of wood"},
      {"f":"aus Metall","b":"(made) of metal"},
      {"f":"bunt","b":"colourful (wie ein Regenbogen)"},
      {"f":"zufrieden","b":"content / satisfied"},
      {"f":"rosa","b":"pink"},
      {"f":"schlafen","b":"to sleep"},
      {"f":"träumen (von)","b":"to dream (of)"},
      {"f":"anfassen","b":"to touch"},
      {"f":"aussehen","b":"to look / appear","ex":"Sie sieht zufrieden aus."}
    ]
  },
  "photo": {
    deck: "DE · Foto beschreiben",
    cards: [
      {"f":"das Bild → die Bilder / das Foto → die Fotos","b":"the picture / the photo"},
      {"f":"die Sonnenbrille → die Sonnenbrillen","b":"the sunglasses"},
      {"f":"das Etui → die Etuis","b":"the case (for glasses)"},
      {"f":"die Kappe → die Kappen","b":"the cap"},
      {"f":"der Hut → die Hüte","b":"the hat"},
      {"f":"das Sofa → die Sofas / die Couch → die Couches","b":"the sofa / couch"},
      {"f":"die Katze → die Katzen","b":"the cat"},
      {"f":"das Buch → die Bücher","b":"book → books"},
      {"f":"die Wanduhr → die Wanduhren","b":"the wall clock"},
      {"f":"der Zeiger → die Zeiger","b":"the clock hand / pointer","ex":"Die Uhr hat zwei Zeiger."},
      {"f":"dick ⇄ dünn","b":"thick ⇄ thin"},
      {"f":"öffnen ⇄ schließen","b":"to open ⇄ to close"},
      {"f":"aufziehen ⇄ abziehen","b":"put on ⇄ take off (glasses/cap)"},
      {"f":"mehr … als","b":"more … than"},
      {"f":"weniger … als","b":"fewer/less … than"},
      {"f":"Wie viel Uhr ist es?","b":"What time is it?"}
    ]
  },
  "houses": {
    deck: "DE · Die Häuser",
    cards: [
      {"f":"das Haus → die Häuser","b":"house → houses"},
      {"f":"das Dach → die Dächer","b":"roof → roofs","ex":"Jedes Haus hat ein Dach."},
      {"f":"der Schornstein → die Schornsteine","b":"the chimney","ex":"Aus dem Schornstein kommt Rauch."},
      {"f":"der Rauch (kein Plural)","b":"the smoke"},
      {"f":"das Fenster → die Fenster","b":"window → windows (no change)"},
      {"f":"der Himmel → die Himmel","b":"the sky","ex":"Der Himmel ist blau."},
      {"f":"oben ⇄ unten","b":"top ⇄ bottom / up ⇄ down"},
      {"f":"links ⇄ rechts","b":"left ⇄ right"},
      {"f":"zwischen … und …","b":"between … and … (+ dative)"},
      {"f":"dazwischen","b":"in between (the two)"},
      {"f":"rosa","b":"pink"},
      {"f":"gelb","b":"yellow"},
      {"f":"blau","b":"blue"}
    ]
  },
  "childdog": {
    deck: "DE · Kind, Hund & Blume",
    cards: [
      {"f":"das Kind → die Kinder","b":"the child"},
      {"f":"der Hund → die Hunde","b":"the dog","ex":"Der Hund hat einen Hut auf."},
      {"f":"der Hut → die Hüte","b":"the hat"},
      {"f":"das Glas → die Gläser","b":"the glass","ex":"In dem Glas ist Wasser."},
      {"f":"die Blume → die Blumen","b":"the flower","ex":"Die Blume steht im Glas."},
      {"f":"das Blatt → die Blätter","b":"leaf → leaves","ex":"Die Blume hat zwei Blätter."},
      {"f":"die Wolke → die Wolken","b":"the cloud","ex":"Die Wolke schwebt über der Blume."},
      {"f":"der Regen (kein Plural)","b":"the rain","ex":"Aus der Wolke fällt Regen."},
      {"f":"über (+ Dativ)","b":"above / over","ex":"über der Blume"},
      {"f":"unter (+ Dativ)","b":"below / under","ex":"unter der Wolke"},
      {"f":"anschauen","b":"to look at","ex":"Das Kind schaut die Blume an."},
      {"f":"schweben","b":"to float / hover"},
      {"f":"fallen","b":"to fall"}
    ]
  },
  "livingroom": {
    deck: "DE · Das Wohnzimmer",
    cards: [
      {"f":"das Wohnzimmer → die Wohnzimmer","b":"the living room"},
      {"f":"das Sofa → die Sofas","b":"the sofa","ex":"Auf dem Sofa liegen fünf Kissen."},
      {"f":"das Kissen → die Kissen","b":"cushion → cushions (no change)"},
      {"f":"die Lampe → die Lampen","b":"the lamp","ex":"Die Lampe steht neben dem Sofa."},
      {"f":"der Lampenschirm → die Lampenschirme","b":"the lampshade"},
      {"f":"die Glühbirne → die Glühbirnen","b":"the light bulb"},
      {"f":"der Tisch → die Tische","b":"the table"},
      {"f":"die Vase → die Vasen","b":"the vase","ex":"In der Vase steht eine Blume."},
      {"f":"die Blume → die Blumen","b":"the flower"},
      {"f":"die Flasche → die Flaschen","b":"the bottle"},
      {"f":"der Bilderrahmen → die Bilderrahmen","b":"the picture frame","ex":"Die Bilderrahmen hängen an der Wand."},
      {"f":"der Boden → die Böden","b":"the floor"},
      {"f":"die Wand → die Wände","b":"the wall"},
      {"f":"die Decke → die Decken","b":"the ceiling"},
      {"f":"der Streifen → die Streifen","b":"the stripes"},
      {"f":"der Punkt → die Punkte","b":"the dots"},
      {"f":"groß ⇄ klein","b":"big ⇄ small"},
      {"f":"die Mitte (kein Plural)","b":"the middle","ex":"Das Kissen liegt in der Mitte."},
      {"f":"neben","b":"next to (+ Dativ)"}
    ]
  },
  "beach": {
    deck: "DE · Am Strand",
    cards: [
      {"f":"die Frau → die Frauen","b":"woman → women"},
      {"f":"das Handtuch → die Handtücher","b":"the towel","ex":"Die drei Frauen sitzen auf einem Handtuch."},
      {"f":"der Badeanzug → die Badeanzüge","b":"swimsuit → swimsuits"},
      {"f":"der Hut → die Hüte","b":"hat → hats"},
      {"f":"der Strand → die Strände","b":"the beach (am Strand = at the beach)"},
      {"f":"rot","b":"red"},
      {"f":"orange / orangen-","b":"orange (adj: ein orangener …)"},
      {"f":"türkis","b":"turquoise"},
      {"f":"pink","b":"pink (bright/hot pink)"},
      {"f":"ein roter Badeanzug","b":"a red swimsuit (masc. -er ending)"},
      {"f":"auf der linken Seite","b":"on the left side"},
      {"f":"auf der rechten Seite","b":"on the right side"},
      {"f":"in der Mitte","b":"in the middle"},
      {"f":"lang ⇄ kurz","b":"long ⇄ short"}
    ]
  },
  "apple": {
    deck: "DE · Apfel schneiden",
    cards: [
      {"f":"der Apfel → die Äpfel","b":"apple → apples","ex":"Der Apfel ist rot."},
      {"f":"der Stiel → die Stiele","b":"the stem"},
      {"f":"die Schale → die Schalen","b":"the peel / skin","ex":"Ich mag die Schale — sie ist gesund."},
      {"f":"der Kern → die Kerne","b":"seed / pip → seeds"},
      {"f":"das Kerngehäuse → die Kerngehäuse","b":"the core","ex":"Ich schneide das Kerngehäuse heraus."},
      {"f":"das Messer → die Messer","b":"the knife (Griff = handle, Schneide = blade)"},
      {"f":"das Schneidebrett → die Schneidebretter","b":"the cutting board","ex":"Das Schneidebrett ist aus Holz."},
      {"f":"die Schüssel → die Schüsseln","b":"the bowl","ex":"Ich lege die Stücke in die Schüssel."},
      {"f":"die Scheibe → die Scheiben","b":"the slice"},
      {"f":"das Stück → die Stücke","b":"the piece"},
      {"f":"ganz / halb / ein Viertel","b":"whole / half / a quarter"},
      {"f":"innen ⇄ außen","b":"inside ⇄ outside"},
      {"f":"schneiden","b":"to cut"},
      {"f":"schälen","b":"to peel"},
      {"f":"halbieren","b":"to halve"},
      {"f":"durchschneiden","b":"to cut through"},
      {"f":"aus Holz / aus Metall","b":"of wood / of metal"}
    ]
  },
  "pencilcase": {
    deck: "DE · Mäppchen & Stifte",
    cards: [
      {"f":"das Mäppchen → die Mäppchen","b":"the pencil case"},
      {"f":"der Reißverschluss → die Reißverschlüsse","b":"the zip / zipper","ex":"Mit dem Reißverschluss kann man das Mäppchen zumachen."},
      {"f":"der Bleistift → die Bleistifte","b":"the pencil","ex":"Mit dem Bleistift kann ich schreiben."},
      {"f":"der Buntstift → die Buntstifte","b":"the coloured pencil"},
      {"f":"der Füller → die Füller","b":"the fountain pen"},
      {"f":"der Filzstift → die Filzstifte","b":"the felt-tip pen"},
      {"f":"der Fineliner → die Fineliner","b":"the fineliner"},
      {"f":"der Textmarker → die Textmarker","b":"the highlighter","ex":"Mit dem Textmarker kann man Text markieren."},
      {"f":"die Kappe → die Kappen","b":"the cap (of a pen)"},
      {"f":"das Lineal → die Lineale","b":"the ruler","ex":"Mit dem Lineal kann man Linien ziehen."},
      {"f":"die Linie → die Linien","b":"line → lines"},
      {"f":"das Papier → die Papiere","b":"the paper (liniert / kariert)"},
      {"f":"gleich ⇄ unterschiedlich","b":"the same ⇄ different"},
      {"f":"die Farbe → die Farben","b":"the colour"},
      {"f":"die Form → die Formen","b":"the shape"},
      {"f":"dick ⇄ dünn","b":"thick ⇄ thin"},
      {"f":"lang ⇄ kurz","b":"long ⇄ short"},
      {"f":"liniert / kariert","b":"lined / squared (paper)"}
    ]
  },
  "weatherweek": {
    deck: "DE · Wetter & Woche",
    cards: [
      {"f":"der Montag → die Montage","b":"Monday"},
      {"f":"der Dienstag → die Dienstage","b":"Tuesday"},
      {"f":"der Mittwoch → die Mittwoche","b":"Wednesday"},
      {"f":"der Donnerstag → die Donnerstage","b":"Thursday"},
      {"f":"der Freitag → die Freitage","b":"Friday"},
      {"f":"der Samstag → die Samstage","b":"Saturday"},
      {"f":"der Sonntag → die Sonntage","b":"Sunday"},
      {"f":"die Sonne → die Sonnen — sonnig","b":"sun — sunny","ex":"Die Sonne scheint."},
      {"f":"die Wolke → die Wolken — wolkig","b":"cloud — cloudy"},
      {"f":"der Regen (kein Plural) — es regnet","b":"rain — it's raining"},
      {"f":"der Wind → die Winde — windig","b":"wind — windy"},
      {"f":"das Gewitter → die Gewitter — es gewittert","b":"thunderstorm — it's storming"},
      {"f":"der Schnee (kein Plural) — es schneit","b":"snow — it's snowing"},
      {"f":"heiß / warm / kalt","b":"hot / warm / cold"},
      {"f":"gestern / heute / morgen","b":"yesterday / today / tomorrow"},
      {"f":"vorgestern / übermorgen","b":"day before yesterday / day after tomorrow"},
      {"f":"es war / es ist / es wird","b":"it was / it is / it will be"},
      {"f":"Wie ist das Wetter?","b":"What's the weather like?"}
    ]
  },
  "wintergirl": {
    deck: "DE · Mädchen im Winter",
    cards: [
      {"f":"das Mädchen → die Mädchen","b":"the girl (-chen → das)"},
      {"f":"die Nase → die Nasen","b":"the nose","ex":"Das Mädchen hat eine rote Nase."},
      {"f":"die Wange → die Wangen","b":"cheek → cheeks","ex":"rote Wangen (red cheeks)"},
      {"f":"der Schnee (kein Plural)","b":"the snow"},
      {"f":"die Schneeflocke → die Schneeflocken","b":"snowflake → snowflakes"},
      {"f":"der Mantel → die Mäntel","b":"the coat","ex":"Sie trägt einen dicken roten Mantel."},
      {"f":"der Schal → die Schals","b":"the scarf"},
      {"f":"der Knopf → die Knöpfe","b":"button → buttons","ex":"Der Mantel hat zwei Knöpfe."},
      {"f":"tragen","b":"to wear (also to carry)","ex":"Was trägt das Mädchen?"},
      {"f":"dick","b":"thick (dicker Mantel)"},
      {"f":"kalt","b":"cold","ex":"Es ist sehr kalt."},
      {"f":"etwas Rotes","b":"something red","ex":"Sie trägt etwas Rotes."}
    ]
  },
  "koerper": {
    deck: "DE · Der Körper",
    cards: [
      {"f":"der Körper → die Körper","b":"the body"},
      {"f":"der Kopf → die Köpfe","b":"the head","ex":"Ich habe Haare am Kopf."},
      {"f":"der Hals → die Hälse","b":"the neck / throat","ex":"Mein Kopf sitzt auf meinem Hals."},
      {"f":"die Schulter → die Schultern","b":"the shoulder","ex":"meine linke und meine rechte Schulter"},
      {"f":"der Arm → die Arme","b":"the arm","ex":"mein linker Arm, mein rechter Arm"},
      {"f":"die Hand → die Hände","b":"hand → hands (umlaut plural)"},
      {"f":"der Finger → die Finger","b":"finger → fingers (NO change)","ex":"fünf Finger an der linken Hand"},
      {"f":"der Daumen → die Daumen","b":"thumb → thumbs (no change)"},
      {"f":"der Bauch → die Bäuche","b":"the belly","ex":"Ich habe Hunger — mein Bauch ist leer."},
      {"f":"der Rücken → die Rücken","b":"the back","ex":"Viele Menschen haben Rückenprobleme."},
      {"f":"das Bein → die Beine","b":"the leg"},
      {"f":"das Knie → die Knie","b":"the knee","ex":"Als Kind habe ich meine Knie oft verletzt."},
      {"f":"der Fuß → die Füße","b":"foot → feet (umlaut plural)"},
      {"f":"der Zeh → die Zehen","b":"toe → toes","ex":"fünf Zehen am linken Fuß"},
      {"f":"greifen","b":"to grip / grab","ex":"Mit den Händen kann man greifen."},
      {"f":"winken","b":"to wave","ex":"Man kann mit der Hand Hallo sagen — winken."},
      {"f":"klatschen","b":"to clap"},
      {"f":"rennen","b":"to run (fast)","ex":"Ich kann schnell laufen — ich kann rennen."},
      {"f":"springen","b":"to jump"},
      {"f":"stampfen","b":"to stamp your feet","ex":"Wenn man wütend ist, kann man stampfen."},
      {"f":"Ich habe Hunger.","b":"I am hungry (lit. I HAVE hunger)"},
      {"f":"mein linker Arm","b":"my left arm (der → -er)"},
      {"f":"mein rechtes Bein","b":"my right leg (das → -es)"}
    ]
  },
  "gesicht": {
    deck: "DE · Das Gesicht",
    cards: [
      {"f":"das Gesicht → die Gesichter","b":"the face"},
      {"f":"das Auge → die Augen","b":"the eye","ex":"Augen können braun, blau oder grün sein."},
      {"f":"das Augenlid → die Augenlider","b":"the eyelid"},
      {"f":"die Augenbraue → die Augenbrauen","b":"the eyebrow"},
      {"f":"das Ohr → die Ohren","b":"the ear","ex":"Mit den Ohren hört man."},
      {"f":"der Ohrring → die Ohrringe","b":"the earring","ex":"das Ohr + der Ring"},
      {"f":"die Nase → die Nasen","b":"the nose","ex":"Mit der Nase riecht man."},
      {"f":"der Mund → die Münder","b":"the mouth (of a PERSON)"},
      {"f":"das Maul → die Mäuler","b":"the mouth of an ANIMAL","ex":"Bei Tieren heißt das Maul."},
      {"f":"die Lippe → die Lippen","b":"the lip","ex":"die Oberlippe und die Unterlippe"},
      {"f":"die Zunge → die Zungen","b":"the tongue","ex":"Mit der Zunge schmeckt man."},
      {"f":"die Wange → die Wangen","b":"the cheek","ex":"Die Wangen werden rot."},
      {"f":"das Kinn → die Kinne","b":"the chin"},
      {"f":"der Kiefer → die Kiefer","b":"the jaw"},
      {"f":"die Stirn → die Stirnen","b":"the forehead"},
      {"f":"sehen","b":"to see","ex":"Mit den Augen sieht man."},
      {"f":"hören","b":"to hear","ex":"Mit den Ohren hört man."},
      {"f":"riechen","b":"to smell","ex":"Mit der Nase riecht man."},
      {"f":"schmecken","b":"to taste","ex":"Mit der Zunge schmeckt man."},
      {"f":"blinzeln","b":"to blink","ex":"Wir blinzeln 15-20 Mal pro Minute."},
      {"f":"atmen","b":"to breathe","ex":"Man atmet mit der Nase."},
      {"f":"küssen","b":"to kiss","ex":"Mit den Lippen kann man küssen."},
      {"f":"werden","b":"to become / to get","ex":"Meine Wangen werden rot."}
    ]
  },
  "personen": {
    deck: "DE · Personen beschreiben",
    cards: [
      {"f":"die Person → die Personen","b":"the person"},
      {"f":"der Mann → die Männer","b":"man → men"},
      {"f":"die Frau → die Frauen","b":"woman → women"},
      {"f":"der Junge → die Jungen","b":"boy → boys"},
      {"f":"das Mädchen → die Mädchen","b":"girl → girls (-chen → das)"},
      {"f":"der Beruf → die Berufe","b":"job / profession","ex":"Was ist sie von Beruf?"},
      {"f":"groß ⇄ klein","b":"tall ⇄ short"},
      {"f":"schlank ⇄ dick","b":"slim ⇄ fat"},
      {"f":"sportlich","b":"sporty / athletic"},
      {"f":"jung ⇄ alt","b":"young ⇄ old"},
      {"f":"die Locke → die Locken","b":"curl → curls","ex":"Sie hat Locken in den Haaren."},
      {"f":"nett","b":"nice / kind","ex":"Sie ist sehr nett."},
      {"f":"schlau (= klug)","b":"clever / smart"},
      {"f":"lustig","b":"funny"},
      {"f":"süß","b":"sweet / cute"},
      {"f":"ruhig","b":"quiet / calm","ex":"Ben ist sehr ruhig."},
      {"f":"schüchtern","b":"shy","ex":"Er ist ein bisschen schüchtern."},
      {"f":"Wie sieht sie aus?","b":"What does she LOOK like? (appearance)"},
      {"f":"Wie ist sie?","b":"What is she LIKE? (character)"},
      {"f":"Sie hat lange blonde Haare.","b":"She has long blond hair (plural → -e)"},
      {"f":"Er hat blaue Augen.","b":"He has blue eyes (plural → -e)"},
      {"f":"Sie ist 33 Jahre alt.","b":"She is 33 years old (sein, not haben)"},
      {"f":"Er ist jünger als sie.","b":"He is younger than her"},
      {"f":"Sie ist Buchautorin.","b":"She is a book author (NO article with jobs)"}
    ]
  },
  "familie": {
    deck: "DE · Die Familie",
    cards: [
      {"f":"die Familie → die Familien","b":"the family"},
      {"f":"die Eltern (nur Plural)","b":"the parents (plural only!)"},
      {"f":"der Vater → die Väter","b":"father → fathers"},
      {"f":"die Mutter → die Mütter","b":"mother → mothers"},
      {"f":"der Sohn → die Söhne","b":"son → sons"},
      {"f":"die Tochter → die Töchter","b":"daughter → daughters"},
      {"f":"der Bruder → die Brüder","b":"brother → brothers"},
      {"f":"die Schwester → die Schwestern","b":"sister → sisters (no umlaut)"},
      {"f":"die Geschwister (nur Plural)","b":"siblings (plural only)"},
      {"f":"die Großeltern (nur Plural)","b":"grandparents (plural only)"},
      {"f":"der Großvater → die Großväter","b":"grandfather (= der Opa)"},
      {"f":"die Großmutter → die Großmütter","b":"grandmother (= die Oma)"},
      {"f":"der Onkel → die Onkel","b":"uncle → uncles (no change)"},
      {"f":"die Tante → die Tanten","b":"aunt → aunts"},
      {"f":"der Neffe → die Neffen","b":"nephew → nephews"},
      {"f":"die Nichte → die Nichten","b":"niece → nieces"},
      {"f":"der Cousin → die Cousins","b":"cousin (male)"},
      {"f":"die Cousine → die Cousinen","b":"cousin (female)"},
      {"f":"verheiratet","b":"married","ex":"Ben ist verheiratet."},
      {"f":"geschieden","b":"divorced","ex":"Emma ist geschieden."},
      {"f":"heiraten","b":"to marry"},
      {"f":"Ben ist der Bruder von Emma.","b":"Ben is Emma's brother (von + Dativ)"},
      {"f":"Emmas Bruder","b":"Emma's brother (-s, NO apostrophe)"}
    ]
  },
  "zaehlen": {
    deck: "DE · Zahlen zählen",
    cards: [
      {"f":"eins, zwei, drei, vier, fünf","b":"1, 2, 3, 4, 5"},
      {"f":"sechs, sieben, acht, neun, zehn","b":"6, 7, 8, 9, 10"},
      {"f":"elf, zwölf","b":"11, 12"},
      {"f":"sechzehn","b":"16 — NOT sechszehn"},
      {"f":"siebzehn","b":"17 — NOT siebenzehn"},
      {"f":"zwanzig","b":"20"},
      {"f":"einundzwanzig","b":"21 — literally one-and-twenty"},
      {"f":"fünfundvierzig","b":"45 — five-and-forty"},
      {"f":"dreißig","b":"30 — spelt with ß"},
      {"f":"hundert / tausend","b":"100 / 1000"},
      {"f":"die Zahl → die Zahlen","b":"the number"},
      {"f":"die Spinne → die Spinnen","b":"the spider","ex":"Eine Spinne hat acht Beine."},
      {"f":"der Raum → die Räume","b":"the room","ex":"Ein Raum hat vier Wände."},
      {"f":"die Wand → die Wände","b":"the wall"},
      {"f":"das Jahr → die Jahre","b":"the year","ex":"Ein Jahr hat zwölf Monate."},
      {"f":"der Monat → die Monate","b":"the month"},
      {"f":"das Jahrzehnt → die Jahrzehnte","b":"the decade","ex":"Ein Jahrzehnt hat zehn Jahre."},
      {"f":"die Mannschaft → die Mannschaften","b":"the team","ex":"Die Mannschaft hat elf Spieler."},
      {"f":"der Spieler → die Spieler","b":"the player (no plural change)"},
      {"f":"der Stern → die Sterne","b":"the star","ex":"vier Sterne auf dem Trikot"},
      {"f":"das Buch → die Bücher","b":"book → books"},
      {"f":"Wie viele Beine hat eine Spinne?","b":"How many legs does a spider have? (wie viele + countable)"},
      {"f":"Wie viel Wasser trinkst du?","b":"How much water do you drink? (wie viel + uncountable)"}
    ]
  },
  "zuhause": {
    deck: "DE · Das Haus",
    cards: [
      {"f":"das Haus → die Häuser","b":"house → houses"},
      {"f":"die Wohnung → die Wohnungen","b":"the flat / apartment (-ung → die)"},
      {"f":"das Zimmer → die Zimmer","b":"the room (no plural change)"},
      {"f":"das Schlafzimmer → die Schlafzimmer","b":"the bedroom (schlafen + Zimmer)"},
      {"f":"das Wohnzimmer → die Wohnzimmer","b":"the living room"},
      {"f":"das Badezimmer → die Badezimmer","b":"the bathroom"},
      {"f":"das Kinderzimmer → die Kinderzimmer","b":"the child's room"},
      {"f":"das Gästezimmer → die Gästezimmer","b":"the guest room"},
      {"f":"die Küche → die Küchen","b":"the kitchen"},
      {"f":"das Büro → die Büros","b":"the office / study"},
      {"f":"das Bett → die Betten","b":"the bed"},
      {"f":"der Kleiderschrank → die Kleiderschränke","b":"the wardrobe"},
      {"f":"der Fernseher → die Fernseher","b":"the TV set","ex":"Der Fernseher steht vor dem Sofa."},
      {"f":"das Bücherregal → die Bücherregale","b":"the bookshelf"},
      {"f":"die Dusche → die Duschen","b":"the shower"},
      {"f":"die Toilette → die Toiletten","b":"the toilet"},
      {"f":"das Waschbecken → die Waschbecken","b":"the washbasin"},
      {"f":"der Garten → die Gärten","b":"the garden"},
      {"f":"der Baum → die Bäume","b":"tree → trees"},
      {"f":"die Blume → die Blumen","b":"the flower"},
      {"f":"das Gras (kein Plural)","b":"the grass"},
      {"f":"der Gast → die Gäste","b":"guest → guests"},
      {"f":"Im Wohnzimmer steht ein Sofa.","b":"In the living room stands a sofa (wo? → Dativ)"},
      {"f":"wohnen vs leben","b":"reside at an address vs be alive / live in a country"}
    ]
  },
  "jedentag": {
    deck: "DE · Jeden Tag",
    cards: [
      {"f":"schlafen","b":"to sleep","ex":"Wir schlafen jede Nacht."},
      {"f":"aufwachen","b":"to wake up (separable)","ex":"Jeden Morgen wachen wir auf."},
      {"f":"aufstehen","b":"to get up (separable)","ex":"Ich stehe um sieben Uhr auf."},
      {"f":"essen","b":"to eat"},
      {"f":"trinken","b":"to drink","ex":"Wie viel trinkst du am Tag?"},
      {"f":"atmen","b":"to breathe","ex":"Wir atmen jeden Tag."},
      {"f":"laufen","b":"to walk / go on foot","ex":"Wir laufen zur Schule."},
      {"f":"fahren","b":"to go by vehicle","ex":"Wir fahren mit dem Auto."},
      {"f":"sitzen ⇄ stehen","b":"to sit ⇄ to stand"},
      {"f":"liegen","b":"to lie (flat)","ex":"Wir liegen im Bett."},
      {"f":"aufmachen ⇄ zumachen","b":"to open ⇄ to close (separable)","ex":"Ich mache die Tür auf."},
      {"f":"die Nacht → die Nächte","b":"night → nights"},
      {"f":"der Morgen → die Morgen","b":"the morning"},
      {"f":"die Stunde → die Stunden","b":"the hour","ex":"sechs bis sieben Stunden"},
      {"f":"die Schule → die Schulen","b":"the school"},
      {"f":"die Arbeit → die Arbeiten","b":"the work / job"},
      {"f":"der Supermarkt → die Supermärkte","b":"the supermarket"},
      {"f":"der Bus → die Busse","b":"bus → buses"},
      {"f":"das Auto → die Autos","b":"the car"},
      {"f":"jeden Tag","b":"every day (accusative time expression)"},
      {"f":"manchmal / immer / nie","b":"sometimes / always / never"},
      {"f":"Ich stehe um sieben Uhr auf.","b":"I get up at seven (prefix goes LAST)"}
    ]
  },
  "woche": {
    deck: "DE · Emmas Woche",
    cards: [
      {"f":"der Montag → die Montage","b":"Monday","ex":"Am Montag macht Emma Yoga."},
      {"f":"der Dienstag → die Dienstage","b":"Tuesday"},
      {"f":"der Mittwoch → die Mittwoche","b":"Wednesday (mid-week)"},
      {"f":"der Donnerstag → die Donnerstage","b":"Thursday"},
      {"f":"der Freitag → die Freitage","b":"Friday"},
      {"f":"der Samstag → die Samstage","b":"Saturday"},
      {"f":"der Sonntag → die Sonntage","b":"Sunday"},
      {"f":"die Woche → die Wochen","b":"the week"},
      {"f":"das Wochenende → die Wochenenden","b":"the weekend"},
      {"f":"am Montag","b":"on Monday (an dem → am, Dativ)"},
      {"f":"morgens / abends","b":"in the mornings / in the evenings"},
      {"f":"nachmittags","b":"in the afternoons"},
      {"f":"einkaufen gehen","b":"to go shopping (separable)","ex":"Sie geht einkaufen."},
      {"f":"putzen","b":"to clean","ex":"Sie putzt die ganze Wohnung."},
      {"f":"tanzen","b":"to dance","ex":"Sie geht zu einem Tanzkurs."},
      {"f":"joggen","b":"to jog","ex":"Freitagmorgen geht sie joggen."},
      {"f":"kochen","b":"to cook","ex":"Sie kochen zusammen Schnitzel."},
      {"f":"sich treffen mit","b":"to meet up with","ex":"Sie trifft sich mit einer Freundin."},
      {"f":"die Kneipe → die Kneipen","b":"the pub"},
      {"f":"das Restaurant → die Restaurants","b":"the restaurant"},
      {"f":"der Tanzkurs → die Tanzkurse","b":"the dance class"},
      {"f":"das Lieblingsessen → die Lieblingsessen","b":"the favourite food"},
      {"f":"Am Montag macht Emma Yoga.","b":"Verb stays SECOND when time comes first"}
    ]
  },
  "tasche": {
    deck: "DE · Meine Tasche",
    cards: [
      {"f":"die Tasche → die Taschen","b":"the bag","ex":"Meine Tasche ist sehr schwer."},
      {"f":"die Sonnenbrille → die Sonnenbrillen","b":"the sunglasses (die Sonne + die Brille)"},
      {"f":"die Maske → die Masken","b":"the mask"},
      {"f":"die Wasserflasche → die Wasserflaschen","b":"the water bottle"},
      {"f":"das Pflaster → die Pflaster","b":"the plaster (no plural change)"},
      {"f":"die Blase → die Blasen","b":"the blister","ex":"Blasenpflaster für die Füße"},
      {"f":"das Taschentuch → die Taschentücher","b":"tissue → tissues (umlaut + -er)"},
      {"f":"die Packung → die Packungen","b":"the pack (-ung → die)"},
      {"f":"der Schlüssel → die Schlüssel","b":"the key (no plural change)"},
      {"f":"der Schlüsselbund → die Schlüsselbunde","b":"the keyring"},
      {"f":"die Sonnencreme → die Sonnencremes","b":"the sun cream"},
      {"f":"der Geldbeutel → die Geldbeutel","b":"the wallet (das Geld + der Beutel)"},
      {"f":"das Geld (kein Plural)","b":"the money"},
      {"f":"die Karte → die Karten","b":"the card"},
      {"f":"der Kassenzettel → die Kassenzettel","b":"the receipt"},
      {"f":"der Kopfhörer → die Kopfhörer","b":"the headphones (der Kopf + der Hörer)"},
      {"f":"der Ohrring → die Ohrringe","b":"the earring"},
      {"f":"die Sache → die Sachen","b":"the thing"},
      {"f":"brauchen","b":"to need (+ Akkusativ)","ex":"Ich brauche meine Sonnencreme."},
      {"f":"aufmachen","b":"to open (separable)","ex":"Ich mache die Tasche auf."},
      {"f":"ein großer Geldbeutel","b":"a big wallet (der → -er)"},
      {"f":"eine kleine Tasche","b":"a small bag (die → -e)"}
    ]
  },
  "tiernamen": {
    deck: "DE · Lustige Tiernamen",
    cards: [
      {"f":"das Tier → die Tiere","b":"the animal"},
      {"f":"das Nashorn → die Nashörner","b":"the rhino (die Nase + das Horn)"},
      {"f":"das Stinktier → die Stinktiere","b":"the skunk (stinken + das Tier)"},
      {"f":"der Waschbär → die Waschbären","b":"the raccoon (waschen + der Bär)"},
      {"f":"die Nacktschnecke → die Nacktschnecken","b":"the slug (nackt + die Schnecke)"},
      {"f":"das Faultier → die Faultiere","b":"the sloth (faul + das Tier)"},
      {"f":"der Bär → die Bären","b":"the bear"},
      {"f":"die Schnecke → die Schnecken","b":"the snail"},
      {"f":"die Haut → die Häute","b":"the skin","ex":"Das Nashorn hat eine graue Haut."},
      {"f":"das Fell → die Felle","b":"the fur (of an animal)"},
      {"f":"der Schwanz → die Schwänze","b":"tail → tails"},
      {"f":"das Horn → die Hörner","b":"horn → horns"},
      {"f":"der Fühler → die Fühler","b":"feeler / antenna","ex":"Die Schnecke hat zwei Fühler."},
      {"f":"der Ast → die Äste","b":"branch → branches"},
      {"f":"faul ⇄ fleißig","b":"lazy ⇄ hard-working"},
      {"f":"langsam ⇄ schnell","b":"slow ⇄ fast"},
      {"f":"schwer ⇄ leicht","b":"heavy ⇄ light"},
      {"f":"nackt","b":"naked","ex":"Die Nacktschnecke hat kein Haus."},
      {"f":"buschig","b":"bushy","ex":"ein buschiger Schwanz"},
      {"f":"gestreift","b":"striped","ex":"schwarz-weiß gestreift"},
      {"f":"stinken","b":"to stink"},
      {"f":"klettern","b":"to climb","ex":"Das Faultier klettert auf Bäume."},
      {"f":"wiegen","b":"to weigh","ex":"Es kann 3000 Kilogramm wiegen."},
      {"f":"langsamer als","b":"slower than (comparative -er + als)"}
    ]
  },
  "gruenetiere": {
    deck: "DE · Grüne Tiere",
    cards: [
      {"f":"die Schildkröte → die Schildkröten","b":"the turtle / tortoise"},
      {"f":"das Krokodil → die Krokodile","b":"the crocodile"},
      {"f":"der Frosch → die Frösche","b":"frog → frogs"},
      {"f":"die Schlange → die Schlangen","b":"the snake"},
      {"f":"der Dinosaurier → die Dinosaurier","b":"the dinosaur (no plural change)"},
      {"f":"das Reptil → die Reptilien","b":"reptile → reptiles (Latin -ien)"},
      {"f":"der Panzer → die Panzer","b":"the shell (of a turtle)"},
      {"f":"die Schuppe → die Schuppen","b":"the scale","ex":"Schuppen wie bei einem Fisch"},
      {"f":"der Zahn → die Zähne","b":"tooth → teeth"},
      {"f":"die Zunge → die Zungen","b":"the tongue"},
      {"f":"das Maul → die Mäuler","b":"mouth of an ANIMAL"},
      {"f":"das Ei → die Eier","b":"egg → eggs"},
      {"f":"der Fluss → die Flüsse","b":"river → rivers"},
      {"f":"der See → die Seen","b":"the LAKE (die See = the sea!)"},
      {"f":"die Pflanze → die Pflanzen","b":"the plant"},
      {"f":"der Pflanzenfresser → die Pflanzenfresser","b":"the herbivore (Pflanzen + fressen)"},
      {"f":"Eier legen","b":"to lay eggs"},
      {"f":"wechseln","b":"to change","ex":"Es wechselt seine Zähne."},
      {"f":"fangen","b":"to catch","ex":"Der Frosch fängt Fliegen."},
      {"f":"aussterben","b":"to go extinct (separable)","ex":"vor 66 Millionen Jahren ausgestorben"},
      {"f":"giftig","b":"poisonous / venomous"},
      {"f":"gefährlich","b":"dangerous"},
      {"f":"glatt / feucht","b":"smooth / damp"},
      {"f":"keine Arme und keine Beine","b":"no arms and no legs (kein, not nicht)"}
    ]
  },
  "liebehasse": {
    deck: "DE · Lieben und hassen",
    cards: [
      {"f":"lieben","b":"to love","ex":"Ich liebe den Sommer."},
      {"f":"mögen","b":"to like","ex":"Ich mag die Berge."},
      {"f":"hassen","b":"to hate","ex":"Ich hasse Kaugummi."},
      {"f":"Das gefällt mir.","b":"I like that (lit. it pleases ME — Dativ)"},
      {"f":"gern","b":"gladly — 'like doing'","ex":"Ich wandere gern."},
      {"f":"der Sommer → die Sommer","b":"the summer"},
      {"f":"die Sonne → die Sonnen","b":"the sun","ex":"Die Sonne scheint."},
      {"f":"die Wärme (kein Plural)","b":"the warmth"},
      {"f":"die Jacke → die Jacken","b":"the jacket"},
      {"f":"der Berg → die Berge","b":"mountain → mountains"},
      {"f":"die Alpen (nur Plural)","b":"the Alps"},
      {"f":"wandern","b":"to hike","ex":"in den Bergen wandern"},
      {"f":"scheinen","b":"to shine","ex":"Die Sonne scheint."},
      {"f":"das Motorrad → die Motorräder","b":"motorbike → motorbikes"},
      {"f":"der Motor → die Motoren","b":"the engine"},
      {"f":"laut ⇄ leise","b":"loud ⇄ quiet"},
      {"f":"der Kaugummi → die Kaugummis","b":"the chewing gum"},
      {"f":"kauen","b":"to chew"},
      {"f":"ekelhaft","b":"disgusting"},
      {"f":"lecker","b":"tasty / delicious"},
      {"f":"schmecken","b":"to taste","ex":"Das schmeckt nicht."},
      {"f":"in die Berge ⇄ in den Bergen","b":"INTO the mountains (Akk) ⇄ IN the mountains (Dat)"}
    ]
  },
  "gruselig": {
    deck: "DE · Gruselige Dinge",
    cards: [
      {"f":"gruselig","b":"creepy / spooky"},
      {"f":"Ich finde Puppen gruselig.","b":"I find dolls creepy (finden + Akk + adjective)"},
      {"f":"die Puppe → die Puppen","b":"the doll"},
      {"f":"das Loch → die Löcher","b":"hole → holes (umlaut + -er)"},
      {"f":"der Ozean → die Ozeane","b":"the ocean"},
      {"f":"der Nebel → die Nebel","b":"the fog (no plural change)"},
      {"f":"die Höhle → die Höhlen","b":"the cave"},
      {"f":"der Clown → die Clowns","b":"the clown"},
      {"f":"der Wald → die Wälder","b":"forest → forests"},
      {"f":"das Blatt → die Blätter","b":"leaf / sheet → leaves / sheets"},
      {"f":"der Gang → die Gänge","b":"passage → passages","ex":"enge Gänge in einer Höhle"},
      {"f":"die Schminke (kein Plural)","b":"make-up"},
      {"f":"aus Plastik / aus Porzellan / aus Stoff","b":"(made) of plastic / porcelain / fabric"},
      {"f":"der Stoff → die Stoffe","b":"the fabric / material"},
      {"f":"dicht","b":"dense / thick (of fog)","ex":"dichter Nebel im Wald"},
      {"f":"eng ⇄ weit","b":"narrow ⇄ wide"},
      {"f":"tief ⇄ flach","b":"deep ⇄ shallow"},
      {"f":"hässlich ⇄ schön","b":"ugly ⇄ beautiful"},
      {"f":"finden","b":"to find / to consider","ex":"Findest du Clowns gruselig?"},
      {"f":"die Leute (nur Plural)","b":"people (plural only)"},
      {"f":"ein Freund von mir","b":"a friend of mine"},
      {"f":"manche Leute","b":"some people"}
    ]
  },
  "schnee": {
    deck: "DE · Im Schnee",
    cards: [
      {"f":"der Schnee (kein Plural)","b":"the snow"},
      {"f":"Es schneit.","b":"It is snowing (empty 'es')"},
      {"f":"der Winter → die Winter","b":"the winter"},
      {"f":"der Schneeball → die Schneebälle","b":"snowball → snowballs"},
      {"f":"die Schneeballschlacht → die Schneeballschlachten","b":"the snowball fight"},
      {"f":"der Schneemann → die Schneemänner","b":"snowman → snowmen"},
      {"f":"der Schneeengel → die Schneeengel","b":"the snow angel"},
      {"f":"der Schlitten → die Schlitten","b":"the sledge (no plural change)"},
      {"f":"der Schlittschuh → die Schlittschuhe","b":"the ice skate"},
      {"f":"Schlitten fahren","b":"to go sledging"},
      {"f":"Schlittschuh laufen","b":"to ice-skate"},
      {"f":"werfen","b":"to throw","ex":"Die Kinder werfen Schneebälle."},
      {"f":"bauen","b":"to build","ex":"Man kann einen Schneemann bauen."},
      {"f":"formen","b":"to form / shape","ex":"einen Schneeball formen"},
      {"f":"sich legen","b":"to lie down","ex":"Man legt sich in den Schnee."},
      {"f":"bewegen","b":"to move","ex":"Man bewegt die Arme."},
      {"f":"anziehen","b":"to put on (separable)","ex":"Du kannst Schlittschuhe anziehen."},
      {"f":"das Dach → die Dächer","b":"roof → roofs"},
      {"f":"der Boden → die Böden","b":"the ground / floor"},
      {"f":"Man kann einen Schneemann bauen.","b":"MODAL: kann second, bauen LAST"},
      {"f":"man","b":"one / you in general (takes er/sie/es form)"},
      {"f":"von oben nach unten","b":"from top to bottom"}
    ]
  },
  "weihnachten": {
    deck: "DE · Weihnachten",
    cards: [
      {"f":"die Weihnachtszeit (kein Plural)","b":"the Christmas season"},
      {"f":"der Adventskalender → die Adventskalender","b":"the advent calendar (24 Türchen)"},
      {"f":"das Türchen → die Türchen","b":"the little door (die Tür + -chen → das)"},
      {"f":"das Plätzchen → die Plätzchen","b":"biscuit / cookie (-chen → das)"},
      {"f":"der Lebkuchen → die Lebkuchen","b":"the gingerbread"},
      {"f":"backen","b":"to bake","ex":"Die Leute backen Plätzchen."},
      {"f":"der Backofen → die Backöfen","b":"the oven"},
      {"f":"der Tannenbaum → die Tannenbäume","b":"the fir tree"},
      {"f":"der Weihnachtsbaum → die Weihnachtsbäume","b":"the Christmas tree"},
      {"f":"die Weihnachtskugel → die Weihnachtskugeln","b":"the bauble"},
      {"f":"schmücken","b":"to decorate","ex":"Wir schmücken den Baum mit Kugeln."},
      {"f":"der Stern → die Sterne","b":"the star","ex":"Der Stern kommt auf die Spitze."},
      {"f":"das Geschenk → die Geschenke","b":"present → presents"},
      {"f":"der Weihnachtsmann → die Weihnachtsmänner","b":"Father Christmas"},
      {"f":"das Rentier → die Rentiere","b":"the reindeer"},
      {"f":"das Weihnachtslied → die Weihnachtslieder","b":"carol → carols (das Lied → die Lieder)"},
      {"f":"der Mistelzweig → die Mistelzweige","b":"the mistletoe"},
      {"f":"singen","b":"to sing","ex":"Die Familie singt Weihnachtslieder."},
      {"f":"der Heiligabend","b":"Christmas Eve — when Germans open presents"},
      {"f":"Es werden viele Plätzchen gebacken.","b":"Many biscuits are baked (PASSIVE: werden + participle)"},
      {"f":"mit Weihnachtskugeln","b":"with baubles (Dativ plural takes -n)"},
      {"f":"Frohe Weihnachten!","b":"Merry Christmas!"}
    ]
  },
  "articles": {
    deck: "DE · der/die/das (Basis)",
    cards: [
      {"f":"___ Stift","b":"der Stift (m.)","ex":"ein roter Stift"},
      {"f":"___ Schere","b":"die Schere (f.)","ex":"eine rote Schere"},
      {"f":"___ Buch","b":"das Buch (n.)","ex":"ein rotes Buch"},
      {"f":"___ Löffel","b":"der Löffel (m.)","ex":"ein kleiner Löffel"},
      {"f":"___ Tasse","b":"die Tasse (f.)","ex":"eine große Tasse"},
      {"f":"___ Messer","b":"das Messer (n.)","ex":"ein großes Messer"},
      {"f":"___ Handy","b":"das Handy (n.)","ex":"ein altes Handy"},
      {"f":"___ Hand","b":"die Hand (f.)","ex":"eine saubere Hand"},
      {"f":"___ Tisch","b":"der Tisch (m.)","ex":"ein runder Tisch"},
      {"f":"ein ___ Stift (rot, m.)","b":"ein roter Stift","ex":"masculine → ‑er"},
      {"f":"eine ___ Schere (rot, f.)","b":"eine rote Schere","ex":"feminine → ‑e"},
      {"f":"ein ___ Buch (rot, n.)","b":"ein rotes Buch","ex":"neuter → ‑es"},
      {"f":"groß ⇄ klein","b":"big ⇄ small"},
      {"f":"alt ⇄ neu","b":"old ⇄ new"},
      {"f":"schmutzig ⇄ sauber","b":"dirty ⇄ clean"},
      {"f":"rund ⇄ eckig","b":"round ⇄ angular/square"}
    ]
  },
  "gender": {
    deck: "DE · Genus-Regeln",
    cards: [
      {"f":"-ung","b":"die (feminine)","ex":"die Bewegung, die Endung"},
      {"f":"-heit / -keit","b":"die","ex":"die Freiheit, die Sicherheit"},
      {"f":"-ei","b":"die","ex":"die Bäckerei, die Polizei"},
      {"f":"-ion","b":"die","ex":"die Aktion, die Religion"},
      {"f":"-tät","b":"die","ex":"die Identität"},
      {"f":"-schaft","b":"die","ex":"die Freundschaft"},
      {"f":"-ie / -ik / -ur","b":"die","ex":"die Energie, die Musik, die Natur"},
      {"f":"-in (person)","b":"die","ex":"die Ärztin, die Studentin"},
      {"f":"-ant / -ent","b":"der (masculine)","ex":"der Student, der Präsident"},
      {"f":"-ling","b":"der","ex":"der Schmetterling, der Zwilling"},
      {"f":"-ismus / -ist / -or","b":"der","ex":"der Tourismus, der Motor"},
      {"f":"-er (mostly)","b":"der","ex":"der Lehrer (but die Butter!)"},
      {"f":"days / months / weather / directions","b":"der","ex":"der Montag, der April, der Regen, der Norden"},
      {"f":"-chen / -lein","b":"das (neuter)","ex":"das Mädchen, das Häuschen"},
      {"f":"-ment","b":"das","ex":"das Dokument, das Medikament"},
      {"f":"-um / -ma","b":"das","ex":"das Datum, das Thema"},
      {"f":"Ge-…","b":"das","ex":"das Gebäude, das Gebirge"},
      {"f":"verb-as-noun","b":"das","ex":"das Leben, das Schwimmen"}
    ]
  },
  "satzbau": {
    deck: "DE · Satzbau",
    cards: [
      {"f":"Rule 1 (main clause)","b":"conjugated verb = position 2","ex":"Heute gehe ich nach Hause."},
      {"f":"position 2 means…","b":"second SLOT, not second word","ex":"An diesem Morgen | gefällt | mir…"},
      {"f":"Rule 2 (objects)","b":"dative before accusative","ex":"Ich gebe dem Mann das Buch."},
      {"f":"Rule 3 (adverbs)","b":"Time → Manner → Place (TMP)","ex":"heute · mit dem Bus · nach Hause"},
      {"f":"Nebensatz rule","b":"verb goes to the END","ex":"…, weil er Gurken liebt."},
      {"f":"weil","b":"because — SUBordinating → verb last","ex":"…, weil er müde ist."},
      {"f":"dass","b":"that — subordinating → verb last","ex":"…, dass er kommt."},
      {"f":"wenn","b":"if/when — subordinating → verb last","ex":"…, wenn es regnet."},
      {"f":"denn","b":"because — COordinating → normal order","ex":"…, denn er liebt Gurken."},
      {"f":"und / aber / oder / denn","b":"coordinating → normal word order after them"}
    ]
  },
  "fragen": {
    deck: "DE · Fragen",
    cards: [
      {"f":"wer","b":"who"},
      {"f":"was","b":"what"},
      {"f":"wo","b":"where"},
      {"f":"wann","b":"when"},
      {"f":"wie","b":"how"},
      {"f":"warum","b":"why"},
      {"f":"woher","b":"from where (movement toward me)","ex":"Woher kommst du?"},
      {"f":"wohin","b":"to where (movement away)","ex":"Wohin gehst du?"},
      {"f":"welche","b":"which","ex":"Welche Farbe magst du?"},
      {"f":"wie viele","b":"how many","ex":"Wie viele Bier hast du?"},
      {"f":"Yes/no question pattern","b":"verb goes FIRST","ex":"Kochst du selber?"},
      {"f":"W-question pattern","b":"W-word, then verb (pos. 2), then rest","ex":"Was kochst du?"}
    ]
  },
  "prep": {
    deck: "DE · an/auf/in",
    cards: [
      {"f":"wo? →","b":"Dativ (location, no movement)","ex":"Ich bin im Wald."},
      {"f":"wohin? →","b":"Akkusativ (movement toward)","ex":"Ich fahre ins Gebirge."},
      {"f":"an + dem","b":"= am","ex":"am See, am Strand"},
      {"f":"an + das","b":"= ans","ex":"ans Meer"},
      {"f":"in + dem","b":"= im","ex":"im Wald"},
      {"f":"in + das","b":"= ins","ex":"ins Gebirge"},
      {"f":"auf + das","b":"= aufs","ex":"aufs Land"},
      {"f":"an (usage)","b":"next to / at an edge","ex":"an der Küste, am Strand (idiom)"},
      {"f":"auf (usage)","b":"physically on top of","ex":"auf dem Land, auf der Insel"},
      {"f":"in (usage)","b":"inside an enclosed area","ex":"im Wald, in Berlin"},
      {"f":"movement to a country/city","b":"use nach (no article)","ex":"nach Deutschland, nach Berlin"},
      {"f":"country WITH article","b":"use in + article","ex":"in die Schweiz, in die USA"}
    ]
  },
  "ausvon": {
    deck: "DE · aus vs von",
    cards: [
      {"f":"aus (rule)","b":"leaving an enclosed space","ex":"aus dem Supermarkt, aus dem Wald"},
      {"f":"von (rule)","b":"from an open point OR a person/institution/event","ex":"von der Bushaltestelle, vom Arzt"},
      {"f":"countries & cities →","b":"always aus","ex":"aus Berlin, aus den USA"},
      {"f":"people / institutions / events →","b":"always von","ex":"vom Arzt, vom Konzert"},
      {"f":"aus dem Park","b":"from the park (enclosed) → aus"},
      {"f":"von der Bushaltestelle","b":"from the bus stop (open point) → von"},
      {"f":"vom Dach / vom Strand","b":"from the roof / beach (open) → von"},
      {"f":"von + dem =","b":"vom"},
      {"f":"both aus & von take…","b":"the Dativ","ex":"aus dem…, von der…"},
      {"f":"aus dem Supermarkt vs vom Supermarkt","b":"the building I left vs the shop/errand (both OK, different emphasis)"}
    ]
  },
  "vorstellen": {
    deck: "DE · Sich vorstellen",
    cards: [
      {"f":"Wie heißt du?","b":"Ich heiße… / Mein Name ist…"},
      {"f":"Wie alt bist du?","b":"Ich bin … (Jahre alt)."},
      {"f":"Woher kommst du?","b":"Ich komme aus…"},
      {"f":"Wo wohnst du?","b":"Ich wohne / lebe in…"},
      {"f":"Seit wann wohnst du hier?","b":"Ich wohne seit … Jahren in…"},
      {"f":"Bist du in einer Beziehung?","b":"Ich bin Single / verheiratet / in einer Beziehung."},
      {"f":"Hast du Kinder?","b":"Ich habe keine Kinder / ein Kind / zwei Kinder."},
      {"f":"Hast du Geschwister?","b":"Ich habe eine Schwester / einen Bruder / bin Einzelkind."},
      {"f":"Was machst du beruflich?","b":"Ich bin… / Ich arbeite als / bei…"},
      {"f":"Was sind deine Hobbys?","b":"Meine Hobbys sind…"},
      {"f":"Machst du Sport?","b":"Ich mache … / Ich fahre Fahrrad / laufe gern."},
      {"f":"Was ist dein Lieblingsessen?","b":"Mein Lieblingsessen ist…"},
      {"f":"Was magst du gar nicht?","b":"Ich mag … nicht. / Ich hasse…"},
      {"f":"Hast du Haustiere?","b":"Ich habe einen Hund / keine Haustiere."},
      {"f":"Welche Musik magst du?","b":"Ich höre gern…"},
      {"f":"Welche Sprachen sprichst du?","b":"Ich spreche Deutsch, Englisch und…"},
      {"f":"…gern (pattern)","b":"verb + gern = 'like doing'","ex":"Ich koche gern."}
    ]
  },
  "felixpark": {
    deck: "DE · Felix im Park",
    cards: [
      {"f":"der Park → die Parks","b":"the park"},
      {"f":"die Bank → die Bänke","b":"bench → benches","ex":"Im Park steht eine Bank."},
      {"f":"der Ball → die Bälle","b":"ball → balls"},
      {"f":"der Fluss → die Flüsse","b":"river → rivers"},
      {"f":"die Brücke → die Brücken","b":"the bridge"},
      {"f":"die Klamotten (nur Plural)","b":"clothes (casual, plural only)"},
      {"f":"die Idee → die Ideen","b":"the idea","ex":"Felix hat eine Idee."},
      {"f":"sich setzen","b":"to sit DOWN (action)","ex":"Felix setzt sich ins Gras."},
      {"f":"sitzen","b":"to sit / be seated (state)","ex":"Er sitzt im Gras."},
      {"f":"schießen","b":"to shoot / kick","ex":"Paul schießt den Ball in einen Baum."},
      {"f":"klettern","b":"to climb","ex":"Felix klettert in den Baum."},
      {"f":"werfen","b":"to throw","ex":"Er wirft den Ball runter."},
      {"f":"springen","b":"to jump","ex":"Felix springt ins Wasser."},
      {"f":"aufhören","b":"to stop (separable)","ex":"Sie hören auf zu spielen."},
      {"f":"nass ⇄ trocken","b":"wet ⇄ dry"},
      {"f":"gefährlich","b":"dangerous","ex":"Klettern ist gefährlich."},
      {"f":"Du sollst nicht klettern!","b":"You're not supposed to climb! (sollen + infinitive last)"},
      {"f":"Du wirst krank.","b":"You'll get ill (werden = become)"},
      {"f":"…, weil die Sonne scheint.","b":"…because the sun is shining (weil → verb LAST)"},
      {"f":"ins Wasser springen","b":"to jump INTO the water (movement → Akkusativ)"}
    ]
  },
  "peterhase": {
    deck: "DE · Peter Hase",
    cards: [
      {"f":"der Hase → die Hasen","b":"hare / rabbit"},
      {"f":"der Vogel → die Vögel","b":"bird → birds"},
      {"f":"die Maus → die Mäuse","b":"mouse → mice"},
      {"f":"der Mensch → die Menschen","b":"human / person"},
      {"f":"die Jacke → die Jacken","b":"the jacket","ex":"Er trägt eine blaue Jacke."},
      {"f":"der Umhang → die Umhänge","b":"the cloak","ex":"einen roten Umhang"},
      {"f":"die Kapuze → die Kapuzen","b":"the hood"},
      {"f":"das Kleid → die Kleider","b":"dress → dresses"},
      {"f":"der Korb → die Körbe","b":"basket → baskets"},
      {"f":"der Regenschirm → die Regenschirme","b":"the umbrella (der Regen + der Schirm)"},
      {"f":"der Zaun → die Zäune","b":"fence → fences"},
      {"f":"die Gießkanne → die Gießkannen","b":"the watering can"},
      {"f":"die Träne → die Tränen","b":"the tear"},
      {"f":"die Karotte → die Karotten","b":"the carrot"},
      {"f":"die Seite → die Seiten","b":"page / side","ex":"Nächste Seite!"},
      {"f":"pflücken","b":"to pick","ex":"Sie pflücken Beeren."},
      {"f":"feststecken","b":"to be stuck (separable)","ex":"Peter steckt im Zaun fest."},
      {"f":"sich verstecken","b":"to hide","ex":"Peter versteckt sich hinter dem Baum."},
      {"f":"ausziehen","b":"to take off (separable)","ex":"Er zieht seine Jacke aus."},
      {"f":"sich ausruhen","b":"to rest (separable)","ex":"Er ruht sich aus."},
      {"f":"wütend","b":"angry"},
      {"f":"erschöpft","b":"exhausted"},
      {"f":"traurig ⇄ glücklich","b":"sad ⇄ happy"},
      {"f":"…, oder?","b":"…, right? (the everyday tag question)"}
    ]
  },
  "schneewittchen": {
    deck: "DE · Schneewittchen",
    cards: [
      {"f":"die Stiefmutter → die Stiefmütter","b":"the stepmother"},
      {"f":"die Königin → die Königinnen","b":"the queen (der König + -in)"},
      {"f":"der Jäger → die Jäger","b":"the huntsman (no plural change)"},
      {"f":"der Zwerg → die Zwerge","b":"dwarf → dwarfs","ex":"die sieben Zwerge"},
      {"f":"der Prinz → die Prinzen","b":"the prince"},
      {"f":"der Spiegel → die Spiegel","b":"the mirror"},
      {"f":"der Wald → die Wälder","b":"forest → forests"},
      {"f":"der Apfel → die Äpfel","b":"apple → apples","ex":"ein giftiger Apfel"},
      {"f":"der Sarg → die Särge","b":"coffin → coffins","ex":"ein Sarg aus Glas"},
      {"f":"das Schloss → die Schlösser","b":"castle → castles"},
      {"f":"böse ⇄ nett","b":"wicked ⇄ nice"},
      {"f":"schmutzig ⇄ sauber","b":"dirty ⇄ clean"},
      {"f":"giftig","b":"poisonous","ex":"Der Apfel ist giftig."},
      {"f":"töten","b":"to kill"},
      {"f":"sterben / gestorben","b":"to die / died"},
      {"f":"sich verwandeln","b":"to transform oneself","ex":"Sie verwandelt sich in eine alte Frau."},
      {"f":"beißen","b":"to bite","ex":"Sie beißt in den Apfel."},
      {"f":"aufwachen","b":"to wake up (separable)","ex":"Schneewittchen wacht auf."},
      {"f":"schöner als","b":"more beautiful than (comparative + als)"},
      {"f":"die Schönste im ganzen Land","b":"the fairest in all the land (superlative)"},
      {"f":"Die Königin will Schneewittchen töten.","b":"wollen + infinitive at the END"},
      {"f":"Es war einmal …","b":"Once upon a time… (simple past of sein)"},
      {"f":"Sie lebten glücklich und zufrieden bis ans Ende ihrer Tage.","b":"They lived happily ever after"}
    ]
  },
  "friedrich": {
    deck: "DE · Der böse Friedrich",
    cards: [
      {"f":"die Geschichte → die Geschichten","b":"the story"},
      {"f":"das Kinderbuch → die Kinderbücher","b":"the children's book"},
      {"f":"böse","b":"wicked / evil","ex":"Friedrich ist böse."},
      {"f":"gemein","b":"mean / cruel","ex":"Er ist gemein zu den Tieren."},
      {"f":"quälen","b":"to torment","ex":"Friedrich quält die Tiere."},
      {"f":"kaputt machen","b":"to break","ex":"Er macht die Stühle kaputt."},
      {"f":"der Flügel → die Flügel","b":"the wing (no plural change)"},
      {"f":"die Fliege → die Fliegen","b":"the fly"},
      {"f":"der Hahn → die Hähne","b":"rooster → roosters"},
      {"f":"die Peitsche → die Peitschen","b":"the whip"},
      {"f":"die Treppe → die Treppen","b":"the stairs"},
      {"f":"schlagen","b":"to hit / beat","ex":"Er schlägt den Hund."},
      {"f":"treten","b":"to kick","ex":"Er tritt den Hund."},
      {"f":"beißen","b":"to bite","ex":"Der Hund beißt Friedrich ins Bein."},
      {"f":"bluten","b":"to bleed","ex":"Das Bein blutet."},
      {"f":"der Schmerz → die Schmerzen","b":"the pain","ex":"Er hat Schmerzen."},
      {"f":"der Arzt → die Ärzte","b":"doctor → doctors"},
      {"f":"die Wurst → die Würste","b":"sausage → sausages"},
      {"f":"der Kuchen → die Kuchen","b":"the cake (no plural change)"},
      {"f":"wegrennen","b":"to run away (separable)","ex":"Der Hund rennt weg."},
      {"f":"Es geht dem Hund gut.","b":"The dog is doing well (es geht + DATIV)"},
      {"f":"Er hat Durst.","b":"He is thirsty (haben, like Hunger)"}
    ]
  },
  "figuren": {
    deck: "DE · Figuren erraten",
    cards: [
      {"f":"erraten","b":"to guess (correctly)","ex":"Könnt ihr die Person erraten?"},
      {"f":"der Bauch → die Bäuche","b":"the belly","ex":"Er hat einen dicken Bauch."},
      {"f":"faul ⇄ fleißig","b":"lazy ⇄ hard-working"},
      {"f":"klug / schlau","b":"clever / smart"},
      {"f":"stark ⇄ schwach","b":"strong ⇄ weak"},
      {"f":"der Nachbar → die Nachbarn","b":"the neighbour (n-noun: den Nachbarn)"},
      {"f":"das Haustier → die Haustiere","b":"the pet"},
      {"f":"das Atomkraftwerk → die Atomkraftwerke","b":"the nuclear power plant"},
      {"f":"die Bibliothek → die Bibliotheken","b":"the library"},
      {"f":"die Hexe → die Hexen","b":"the witch"},
      {"f":"zaubern","b":"to do magic","ex":"Sie kann zaubern."},
      {"f":"der Seemann → die Seemänner","b":"the sailor"},
      {"f":"die Pfeife → die Pfeifen","b":"the pipe","ex":"Er raucht Pfeife."},
      {"f":"rauchen","b":"to smoke"},
      {"f":"der Spinat (kein Plural)","b":"spinach"},
      {"f":"die Mütze → die Mützen","b":"the cap / beanie"},
      {"f":"gewellt","b":"wavy","ex":"lange braune gewellte Haare"},
      {"f":"nur / sehr / ein bisschen","b":"only / very / a bit"},
      {"f":"Er hasst seinen Nachbarn.","b":"He hates his neighbour (n-noun takes -n)"},
      {"f":"Sie ist sehr gut in der Schule.","b":"She is very good at school"}
    ]
  },
  "filme": {
    deck: "DE · Filme erraten",
    cards: [
      {"f":"der Film → die Filme","b":"the film"},
      {"f":"der Dachboden → die Dachböden","b":"the attic"},
      {"f":"der Stromausfall → die Stromausfälle","b":"the power cut"},
      {"f":"der Wecker → die Wecker","b":"the alarm clock","ex":"Der Wecker klingelt nicht."},
      {"f":"der Koffer → die Koffer","b":"the suitcase"},
      {"f":"der Flughafen → die Flughäfen","b":"the airport"},
      {"f":"das Flugzeug → die Flugzeuge","b":"the aeroplane"},
      {"f":"sich streiten","b":"to argue","ex":"Die zwei streiten sich oft."},
      {"f":"vergessen","b":"to forget","ex":"Die Familie vergisst den Jungen."},
      {"f":"der jüngste","b":"the youngest (superlative)"},
      {"f":"der Oger → die Oger","b":"the ogre"},
      {"f":"der Esel → die Esel","b":"the donkey"},
      {"f":"die Prinzessin → die Prinzessinnen","b":"the princess"},
      {"f":"der Drache → die Drachen","b":"the dragon"},
      {"f":"die Burg → die Burgen","b":"the castle / fortress"},
      {"f":"das Geheimnis → die Geheimnisse","b":"the secret"},
      {"f":"retten","b":"to rescue","ex":"Sie müssen die Prinzessin retten."},
      {"f":"bewachen","b":"to guard","ex":"Die Burg wird von einem Drachen bewacht."},
      {"f":"nervig","b":"annoying","ex":"Er findet ihn nervig."},
      {"f":"sich verlieben","b":"to fall in love","ex":"Sie verlieben sich ineinander."},
      {"f":"um … zu retten","b":"in order to rescue (purpose: zu + infinitive last)"},
      {"f":"Ich wünschte, ich hätte keine Familie.","b":"I wish I had no family (Konjunktiv II)"}
    ]
  },
  "tennisspiel": {
    deck: "DE · Das Tennisspiel",
    cards: [
      {"f":"das Museum → die Museen","b":"museum → museums (Latin plural)"},
      {"f":"die Ausstellung → die Ausstellungen","b":"the exhibition (-ung → die)"},
      {"f":"der See → die Seen","b":"the LAKE"},
      {"f":"der Gewinner → die Gewinner","b":"the winner"},
      {"f":"der Punkt → die Punkte","b":"the point","ex":"Tom macht viele Punkte."},
      {"f":"der Tennisschläger → die Tennisschläger","b":"the tennis racket"},
      {"f":"der Keller → die Keller","b":"the cellar / basement"},
      {"f":"gewinnen ⇄ verlieren","b":"to win ⇄ to lose"},
      {"f":"wählen","b":"to choose","ex":"Der Gewinner darf wählen."},
      {"f":"streiten","b":"to argue","ex":"Sie streiten eine halbe Stunde."},
      {"f":"aufholen","b":"to catch up (separable)","ex":"Dann holt Lisa auf."},
      {"f":"einpacken","b":"to pack (separable)","ex":"Tom packt zwei Brötchen ein."},
      {"f":"das Brötchen → die Brötchen","b":"the bread roll (-chen → das)"},
      {"f":"die Straßenbahn → die Straßenbahnen","b":"the tram"},
      {"f":"das Stadtzentrum → die Stadtzentren","b":"the city centre"},
      {"f":"die Stadt → die Städte","b":"city → cities"},
      {"f":"langweilig ⇄ spannend","b":"boring ⇄ exciting"},
      {"f":"lieber","b":"rather / prefer (comparative of gern)","ex":"Sie will lieber zum See."},
      {"f":"Das stimmt nicht.","b":"That's not right."},
      {"f":"gar nicht","b":"not at all"},
      {"f":"zum See / zur Schule","b":"to the lake / to the school (zu + Dativ)"},
      {"f":"das Handy → die Handys","b":"the mobile phone"}
    ]
  },
  "felixschule": {
    deck: "DE · Felix in der Schule",
    cards: [
      {"f":"die Schule → die Schulen","b":"the school"},
      {"f":"der Unterricht (kein Plural)","b":"lessons / class"},
      {"f":"die Lehrerin → die Lehrerinnen","b":"the teacher (female)"},
      {"f":"der Schüler → die Schüler","b":"the pupil (no plural change)"},
      {"f":"die Kantine → die Kantinen","b":"the canteen"},
      {"f":"das Mittagessen → die Mittagessen","b":"lunch (das Essen am Mittag)"},
      {"f":"die Essensschlacht → die Essensschlachten","b":"the food fight"},
      {"f":"anfangen","b":"to begin (separable)","ex":"Die Schule fängt um 8 Uhr an."},
      {"f":"verlassen","b":"to leave (a place)","ex":"Er verlässt das Haus."},
      {"f":"einschlafen","b":"to fall asleep (separable)","ex":"Er schläft im Unterricht ein."},
      {"f":"auslachen","b":"to laugh AT someone (separable)","ex":"Paul lacht ihn aus."},
      {"f":"sich konzentrieren","b":"to concentrate","ex":"Du musst dich konzentrieren."},
      {"f":"wegwerfen","b":"to throw away (separable)","ex":"Er wirft das Essen weg."},
      {"f":"treffen","b":"to meet — OR to hit","ex":"Das Essen trifft Claudia."},
      {"f":"sich schämen","b":"to be ashamed","ex":"Felix schämt sich."},
      {"f":"rechnen","b":"to do sums / calculate"},
      {"f":"müde","b":"tired"},
      {"f":"früh ⇄ spät","b":"early ⇄ late"},
      {"f":"um 8 Uhr","b":"at 8 o'clock"},
      {"f":"auf einmal","b":"all of a sudden"},
      {"f":"deswegen","b":"that's why (triggers verb-second: Deswegen schläft er ein.)"}
    ]
  },
  "keksdieb": {
    deck: "DE · Der Keksdieb",
    cards: [
      {"f":"der Flughafen → die Flughäfen","b":"the airport"},
      {"f":"der Flug → die Flüge","b":"flight → flights"},
      {"f":"das Geschäft → die Geschäfte","b":"the shop"},
      {"f":"der Keks → die Kekse","b":"biscuit → biscuits"},
      {"f":"die Packung → die Packungen","b":"the packet"},
      {"f":"die Hälfte → die Hälften","b":"the half","ex":"Er bricht den Keks in zwei Hälften."},
      {"f":"der Dieb → die Diebe","b":"thief → thieves"},
      {"f":"stehlen","b":"to steal","ex":"Ein Dieb stiehlt Dinge."},
      {"f":"warten auf (+ Akk)","b":"to wait FOR","ex":"Sie wartet auf ihren Flug."},
      {"f":"sich hinsetzen","b":"to sit down (separable)","ex":"Sie setzt sich hin."},
      {"f":"greifen in (+ Akk)","b":"to reach into","ex":"Sie greift in ihre Tasche."},
      {"f":"ignorieren","b":"to ignore"},
      {"f":"brechen","b":"to break","ex":"Er bricht den Keks."},
      {"f":"lächeln","b":"to smile"},
      {"f":"sich entschuldigen bei","b":"to apologise TO someone (+ Dativ)"},
      {"f":"überrascht","b":"surprised"},
      {"f":"erleichtert","b":"relieved"},
      {"f":"unhöflich ⇄ höflich","b":"rude ⇄ polite"},
      {"f":"Jedes Mal, wenn sie einen Keks nimmt, …","b":"Every time she takes a biscuit… (wenn → verb last)"},
      {"f":"Es ist zu spät, um mich zu entschuldigen.","b":"It's too late to apologise (um … zu)"}
    ]
  },
  "wuerttemberg": {
    deck: "DE · Die Prinzessin und der Wirt",
    cards: [
      {"f":"der Kaiser → die Kaiser","b":"the emperor"},
      {"f":"die Prinzessin → die Prinzessinnen","b":"the princess"},
      {"f":"der Diener → die Diener","b":"the servant"},
      {"f":"der Wirt → die Wirte","b":"the innkeeper / landlord"},
      {"f":"der Graf → die Grafen","b":"the count (n-noun: den Grafen)"},
      {"f":"das Wirtshaus → die Wirtshäuser","b":"the inn"},
      {"f":"die Legende → die Legenden","b":"the legend"},
      {"f":"das Bundesland → die Bundesländer","b":"federal state → states"},
      {"f":"sich verlieben in (+ Akk)","b":"to fall in love WITH"},
      {"f":"sich verstecken","b":"to hide"},
      {"f":"wegziehen","b":"to move away (separable)"},
      {"f":"zurückkommen","b":"to come back (separable)"},
      {"f":"übernachten","b":"to stay the night"},
      {"f":"das Lieblingsessen → die Lieblingsessen","b":"the favourite dish"},
      {"f":"akzeptieren","b":"to accept"},
      {"f":"nennen","b":"to call / name","ex":"Ich nenne dich Württemberg."},
      {"f":"wehtun (+ Dativ)","b":"to hurt someone","ex":"Wir wollten dir nicht wehtun."},
      {"f":"froh","b":"glad","ex":"Der Kaiser war so froh."},
      {"f":"lebte / war / hatte / sagte","b":"SIMPLE PAST: lived / was / had / said"},
      {"f":"so gut … wie","b":"as well as (equality: so … wie)"},
      {"f":"der Wirt am Berg → Württemberg","b":"the pun the legend is built on"}
    ]
  },
  "ichmag": {
    deck: "DE · Dinge, die ich mag",
    cards: [
      {"f":"die Frucht → die Früchte","b":"fruit → fruits"},
      {"f":"die Banane → die Bananen","b":"the banana"},
      {"f":"die Kirsche → die Kirschen","b":"the cherry"},
      {"f":"die Blaubeere → die Blaubeeren","b":"the blueberry"},
      {"f":"die Ananas → die Ananas","b":"the pineapple (no plural change)"},
      {"f":"das Gemüse → die Gemüse","b":"vegetables"},
      {"f":"die Tomate → die Tomaten","b":"the tomato"},
      {"f":"die Aubergine → die Auberginen","b":"the aubergine"},
      {"f":"das Fleisch (kein Plural)","b":"meat"},
      {"f":"die Decke → die Decken","b":"the blanket (also: ceiling)"},
      {"f":"wärmen","b":"to warm","ex":"Der Tee wärmt mich."},
      {"f":"die Musik (kein Plural)","b":"music"},
      {"f":"das Instrument → die Instrumente","b":"the instrument"},
      {"f":"die Trommel → die Trommeln","b":"the drum"},
      {"f":"die Gitarre → die Gitarren","b":"the guitar"},
      {"f":"die Flöte → die Flöten","b":"the flute"},
      {"f":"die Serie → die Serien","b":"the TV series"},
      {"f":"reisen","b":"to travel"},
      {"f":"die Spülmaschine → die Spülmaschinen","b":"the dishwasher"},
      {"f":"das Geschirr (kein Plural)","b":"dishes / crockery"},
      {"f":"meine Lieblingsfrucht","b":"my favourite fruit (Lieblings- + noun)"},
      {"f":"die meisten Leute","b":"most people"},
      {"f":"lieber … als","b":"prefer X to Y","ex":"Sie mögen Kaffee lieber als Tee."},
      {"f":"ungefähr","b":"approximately"}
    ]
  },
  "grossbritannien": {
    deck: "DE · Großbritannien",
    cards: [
      {"f":"das Land → die Länder","b":"country → countries"},
      {"f":"die Hauptstadt → die Hauptstädte","b":"the capital city"},
      {"f":"die Stadt → die Städte","b":"city → cities"},
      {"f":"die Landschaft → die Landschaften","b":"the landscape"},
      {"f":"die Sprache → die Sprachen","b":"the language"},
      {"f":"der Akzent → die Akzente","b":"the accent"},
      {"f":"der Humor (kein Plural)","b":"humour","ex":"Ich mag den britischen Humor."},
      {"f":"die Leute (nur Plural)","b":"people (plural only)"},
      {"f":"der Brite → die Briten","b":"the Briton (n-noun)"},
      {"f":"die Kneipe → die Kneipen","b":"the pub"},
      {"f":"britisch / deutsch / englisch","b":"British / German / English (lower case adjectives)"},
      {"f":"Englisch (die Sprache)","b":"English — the LANGUAGE is capitalised"},
      {"f":"unterschiedlich","b":"different / varied"},
      {"f":"vielseitig","b":"diverse / versatile"},
      {"f":"klingen","b":"to sound","ex":"Das klingt anders."},
      {"f":"ziehen nach","b":"to move to (a place)","ex":"Ich bin nach England gezogen."},
      {"f":"Es gibt …","b":"There is / there are (+ AKKUSATIV, always singular gibt)"},
      {"f":"in der Schweiz / in den USA","b":"the few countries that DO take an article"},
      {"f":"der Norden / der Süden / der Osten / der Westen","b":"north / south / east / west"},
      {"f":"schwarzer Tee mit Milch ohne Zucker","b":"black tea with milk, no sugar"}
    ]
  },
  "hoeflich": {
    deck: "DE · Höflich und unhöflich",
    cards: [
      {"f":"höflich ⇄ unhöflich","b":"polite ⇄ rude"},
      {"f":"pünktlich ⇄ unpünktlich","b":"punctual ⇄ late"},
      {"f":"Guten Appetit!","b":"Enjoy your meal! (say it BEFORE eating)"},
      {"f":"Danke, gleichfalls!","b":"Thanks, you too! (the standard reply)"},
      {"f":"der Kellner → die Kellner","b":"the waiter"},
      {"f":"sich verabreden","b":"to arrange to meet","ex":"Sie verabreden sich für 18 Uhr."},
      {"f":"der Hausschuh → die Hausschuhe","b":"the slipper"},
      {"f":"der Straßenschuh → die Straßenschuhe","b":"the outdoor shoe"},
      {"f":"ausziehen","b":"to take off (separable)","ex":"Man zieht die Schuhe aus."},
      {"f":"der Dreck (kein Plural)","b":"dirt"},
      {"f":"dreckig ⇄ sauber","b":"dirty ⇄ clean"},
      {"f":"der Lärm (kein Plural)","b":"noise"},
      {"f":"die Ruhe (kein Plural)","b":"quiet / rest"},
      {"f":"der Ruhetag → die Ruhetage","b":"day of rest — Sunday in Germany"},
      {"f":"Rasen mähen","b":"to mow the lawn — NOT on a Sunday"},
      {"f":"auf dem Land ⇄ in der Stadt","b":"in the countryside ⇄ in the city"},
      {"f":"sich unterhalten","b":"to have a conversation"},
      {"f":"sich ausruhen","b":"to rest (separable)"},
      {"f":"Es ist höflich, die Schuhe auszuziehen.","b":"It's polite to take your shoes off (zu INSIDE the verb)"},
      {"f":"die Öffentlichkeit","b":"the public sphere","ex":"Lärm in der Öffentlichkeit"}
    ]
  },
  "martinstag": {
    deck: "DE · Der Martinstag",
    cards: [
      {"f":"die Tradition → die Traditionen","b":"the tradition"},
      {"f":"der Martinstag","b":"St. Martin's Day — 11 November"},
      {"f":"die Laterne → die Laternen","b":"the lantern"},
      {"f":"der Umzug → die Umzüge","b":"the procession"},
      {"f":"das Lied → die Lieder","b":"song → songs"},
      {"f":"die Brezel → die Brezeln","b":"the pretzel"},
      {"f":"die Gans → die Gänse","b":"goose → geese"},
      {"f":"der Gänsebraten → die Gänsebraten","b":"the roast goose"},
      {"f":"der Heilige → die Heiligen","b":"the saint"},
      {"f":"der Bischof → die Bischöfe","b":"bishop → bishops"},
      {"f":"der Bettler → die Bettler","b":"the beggar"},
      {"f":"der Mantel → die Mäntel","b":"cloak / coat → coats"},
      {"f":"die Hälfte → die Hälften","b":"the half"},
      {"f":"das Pferd → die Pferde","b":"the horse"},
      {"f":"feiern","b":"to celebrate"},
      {"f":"basteln","b":"to make / craft","ex":"Die Kinder basteln Laternen."},
      {"f":"reiten","b":"to ride a horse"},
      {"f":"durchschneiden","b":"to cut through (separable)"},
      {"f":"frieren","b":"to be cold / freeze","ex":"Der Bettler hat gefroren."},
      {"f":"am 11. November","b":"on the 11th of November (am elften November)"},
      {"f":"Der Martinstag wird gefeiert.","b":"St Martin's Day IS CELEBRATED (passive)"},
      {"f":"Er wurde beerdigt.","b":"He was buried (past passive: wurde + participle)"}
    ]
  },
  "mode": {
    deck: "DE · Modetrends",
    cards: [
      {"f":"die Mode → die Moden","b":"fashion"},
      {"f":"die Hose → die Hosen","b":"TROUSERS — singular in German! (eine Hose)"},
      {"f":"die Schlaghose → die Schlaghosen","b":"flared trousers"},
      {"f":"die Hüfthose → die Hüfthosen","b":"hipster trousers"},
      {"f":"die Jeansjacke → die Jeansjacken","b":"the denim jacket"},
      {"f":"das Oberteil → die Oberteile","b":"the top (garment)"},
      {"f":"der Träger → die Träger","b":"the strap","ex":"Spaghettiträger"},
      {"f":"das Halsband → die Halsbänder","b":"the choker"},
      {"f":"die Bauchtasche → die Bauchtaschen","b":"the bum bag"},
      {"f":"die Creole → die Creolen","b":"the hoop earring"},
      {"f":"der Stoff → die Stoffe","b":"the fabric"},
      {"f":"das Muster → die Muster","b":"the pattern"},
      {"f":"die Hüfte → die Hüften","b":"the hip"},
      {"f":"eng ⇄ weit","b":"tight ⇄ loose / wide"},
      {"f":"dunkelblau ⇄ hellblau","b":"dark blue ⇄ light blue"},
      {"f":"bauchfrei","b":"midriff-baring","ex":"ein bauchfreies Top"},
      {"f":"angesagt / in","b":"trendy / in fashion"},
      {"f":"damals ⇄ heute","b":"back then ⇄ today"},
      {"f":"wieder","b":"again","ex":"Jetzt sind sie wieder angesagt."},
      {"f":"die Grundschule → die Grundschulen","b":"primary school (years 1-4)"},
      {"f":"bedeuten","b":"to mean","ex":"Was bedeutet bauchfrei?"},
      {"f":"…, dass der Bauch nicht bedeckt ist.","b":"…that the belly isn't covered (dass → verb LAST)"}
    ]
  },
  "kassetten": {
    deck: "DE · Kassetten aus der Kindheit",
    cards: [
      {"f":"die Kassette → die Kassetten","b":"the cassette"},
      {"f":"das Hörspiel → die Hörspiele","b":"the audio drama"},
      {"f":"die Reihe → die Reihen","b":"the series"},
      {"f":"die Hexe → die Hexen","b":"the witch","ex":"Bibi Blocksberg ist eine Hexe."},
      {"f":"hexen / zaubern","b":"to do witchcraft / magic"},
      {"f":"das Gespenst → die Gespenster","b":"ghost → ghosts"},
      {"f":"spuken","b":"to haunt","ex":"Hui Buh spukt um Mitternacht."},
      {"f":"erschrecken","b":"to frighten"},
      {"f":"das Schloss → die Schlösser","b":"castle → castles"},
      {"f":"der Turm → die Türme","b":"tower → towers"},
      {"f":"der Ritter → die Ritter","b":"the knight (no plural change)"},
      {"f":"der Erbe → die Erben","b":"the heir"},
      {"f":"der Vorfahre → die Vorfahren","b":"the ancestor"},
      {"f":"der Bauernhof → die Bauernhöfe","b":"the farm"},
      {"f":"das Huhn → die Hühner","b":"chicken → chickens"},
      {"f":"die Ferien (nur Plural)","b":"school holidays (plural only)"},
      {"f":"der Jugendliche → die Jugendlichen","b":"the teenager (14-18)"},
      {"f":"das Gedächtnis → die Gedächtnisse","b":"the memory"},
      {"f":"sich erinnern an (+ Akk)","b":"to remember"},
      {"f":"der Kriminalfall → die Kriminalfälle","b":"the criminal case"},
      {"f":"lösen","b":"to solve","ex":"Sie lösen Kriminalfälle."},
      {"f":"gehören (+ Dativ)","b":"to belong TO","ex":"Das Schloss gehört mir."},
      {"f":"mutig / gerecht","b":"brave / fair"},
      {"f":"ein 13-jähriges Mädchen","b":"a 13-year-old girl"}
    ]
  },
  "laender": {
    deck: "DE · Länder erraten",
    cards: [
      {"f":"das Nachbarland → die Nachbarländer","b":"the neighbouring country"},
      {"f":"die Insel → die Inseln","b":"the island"},
      {"f":"der Einwohner → die Einwohner","b":"the inhabitant"},
      {"f":"die Flagge → die Flaggen","b":"the flag"},
      {"f":"die Fläche → die Flächen","b":"the area"},
      {"f":"der Regenwald → die Regenwälder","b":"the rainforest"},
      {"f":"die Wüste → die Wüsten","b":"the desert"},
      {"f":"der Sand (kein Plural)","b":"sand"},
      {"f":"das Meer → die Meere","b":"the sea"},
      {"f":"der Strand → die Strände","b":"beach → beaches"},
      {"f":"die Pyramide → die Pyramiden","b":"the pyramid"},
      {"f":"das Kamel → die Kamele","b":"the camel"},
      {"f":"das Grab → die Gräber","b":"grave → graves"},
      {"f":"die Monarchie → die Monarchien","b":"the monarchy"},
      {"f":"die Weltmeisterschaft → die Weltmeisterschaften","b":"the World Cup"},
      {"f":"der Zug → die Züge","b":"train → trains"},
      {"f":"das Ahornblatt → die Ahornblätter","b":"the maple leaf"},
      {"f":"trocken ⇄ nass","b":"dry ⇄ wet"},
      {"f":"bekannt für (+ Akk)","b":"famous FOR"},
      {"f":"erfinden","b":"to invent","ex":"Karaoke wurde dort erfunden."},
      {"f":"10,3 Millionen","b":"zehn KOMMA drei Millionen — comma is the decimal point"},
      {"f":"die zweitgrößte Fläche","b":"the second-largest area"},
      {"f":"Deutschland hat neun Nachbarländer.","b":"Germany has nine neighbouring countries"}
    ]
  },
  "deutschzahlen": {
    deck: "DE · Deutsch in Zahlen",
    cards: [
      {"f":"die Muttersprache → die Muttersprachen","b":"the native language"},
      {"f":"die Zweitsprache → die Zweitsprachen","b":"the second language"},
      {"f":"die Amtssprache → die Amtssprachen","b":"the official language"},
      {"f":"der Muttersprachler → die Muttersprachler","b":"the native speaker"},
      {"f":"der Mensch → die Menschen","b":"person → people (n-noun)"},
      {"f":"die Welt (kein Plural)","b":"the world"},
      {"f":"weltweit","b":"worldwide"},
      {"f":"insgesamt","b":"in total / altogether"},
      {"f":"im Moment","b":"at the moment"},
      {"f":"irgendwann","b":"at some point"},
      {"f":"auf Platz elf","b":"in eleventh place"},
      {"f":"die meistgesprochenen Sprachen","b":"the most spoken languages"},
      {"f":"die meistverbreitete Muttersprache","b":"the most widespread native language"},
      {"f":"die zweitbeliebteste Sprache","b":"the second most popular language"},
      {"f":"Deutsch wird in Deutschland gesprochen.","b":"German IS SPOKEN in Germany (passive)"},
      {"f":"Deutschland, Österreich, die Schweiz","b":"three of the German-speaking countries"},
      {"f":"Liechtenstein, Belgien, Luxemburg","b":"the other three official-language countries"},
      {"f":"130 Millionen","b":"native + second-language speakers worldwide"},
      {"f":"15,4 Millionen","b":"people currently learning German"}
    ]
  },
  "deutschlandfakten": {
    deck: "DE · Deutschland in Zahlen",
    cards: [
      {"f":"der Einwohner → die Einwohner","b":"the inhabitant","ex":"83 Millionen Einwohner"},
      {"f":"der Haushalt → die Haushalte","b":"the household"},
      {"f":"der Einwanderer ⇄ der Auswanderer","b":"immigrant ⇄ emigrant"},
      {"f":"männlich ⇄ weiblich","b":"male ⇄ female"},
      {"f":"die Fläche → die Flächen","b":"the area"},
      {"f":"der Quadratkilometer → die Quadratkilometer","b":"the square kilometre"},
      {"f":"der Wald → die Wälder","b":"forest → forests"},
      {"f":"die Küste → die Küsten","b":"the coast","ex":"Die Küste ist 2442 km lang."},
      {"f":"die Nordsee / die Ostsee","b":"the North Sea / the Baltic (die See → feminine)"},
      {"f":"der Rhein","b":"the Rhine — Germany's longest river"},
      {"f":"die Zugspitze","b":"Germany's highest mountain, 2962 m"},
      {"f":"das Grundgesetz","b":"the Basic Law — Germany's constitution"},
      {"f":"das Gesetz → die Gesetze","b":"the law"},
      {"f":"der Artikel → die Artikel","b":"the article","ex":"146 Artikel im Grundgesetz"},
      {"f":"liegen","b":"to be situated","ex":"Deutschland liegt am Meer."},
      {"f":"2962 Meter hoch","b":"2962 metres high (unit stays SINGULAR)"},
      {"f":"865 Kilometer lang","b":"865 kilometres long"},
      {"f":"der längste Fluss","b":"the longest river"},
      {"f":"der höchste Berg","b":"the highest mountain"},
      {"f":"83 Millionen Einwohner","b":"Germany's population"}
    ]
  },
  "autobahn": {
    deck: "DE · Die Autobahn",
    cards: [
      {"f":"die Autobahn → die Autobahnen","b":"the motorway"},
      {"f":"das Tempolimit → die Tempolimits","b":"the speed limit"},
      {"f":"die Richtgeschwindigkeit","b":"the ADVISORY speed — 130 km/h, not binding"},
      {"f":"der Stau → die Staus","b":"the traffic jam"},
      {"f":"die Spur → die Spuren","b":"the lane"},
      {"f":"die Rettungsgasse → die Rettungsgassen","b":"the emergency corridor (legally required)"},
      {"f":"der Unfall → die Unfälle","b":"accident → accidents"},
      {"f":"der Krankenwagen → die Krankenwagen","b":"the ambulance"},
      {"f":"die Feuerwehr → die Feuerwehren","b":"the fire brigade"},
      {"f":"die Polizei (kein Plural)","b":"the police"},
      {"f":"die Ziffer → die Ziffern","b":"the digit"},
      {"f":"gerade ⇄ ungerade","b":"even ⇄ odd (numbers)"},
      {"f":"empfehlen","b":"to recommend","ex":"Es wird empfohlen."},
      {"f":"bilden","b":"to form","ex":"Eine Rettungsgasse muss gebildet werden."},
      {"f":"trotzdem","b":"nevertheless (triggers inversion)"},
      {"f":"wahrscheinlich","b":"probably"},
      {"f":"sogar","b":"even","ex":"sogar die längste in Europa"},
      {"f":"überall","b":"everywhere"},
      {"f":"60 Prozent","b":"60 per cent (Prozent stays singular)"},
      {"f":"Nur 60% der Autobahn hat kein Tempolimit.","b":"The corrected famous fact"},
      {"f":"gerade Ziffer → Ost-West","b":"even number = east-west route"},
      {"f":"ungerade Ziffer → Nord-Süd","b":"odd number = north-south route"}
    ]
  },
  "bilderbuch": {
    deck: "DE · Bilder im Buch",
    cards: [
      {"f":"das Bilderbuch → die Bilderbücher","b":"the picture book"},
      {"f":"die Seite → die Seiten","b":"the page","ex":"Nächste Seite!"},
      {"f":"das Ei → die Eier","b":"egg → eggs"},
      {"f":"das Huhn → die Hühner","b":"chicken → chickens"},
      {"f":"die Brille → die Brillen","b":"the glasses (SINGULAR in German)"},
      {"f":"die Träne → die Tränen","b":"the tear","ex":"Da sind zwei Tränen."},
      {"f":"der Kessel → die Kessel","b":"the kettle / cauldron"},
      {"f":"der Krug → die Krüge","b":"jug → jugs"},
      {"f":"die Schüssel → die Schüsseln","b":"the bowl"},
      {"f":"der Löffel → die Löffel","b":"the spoon"},
      {"f":"die Mauer → die Mauern","b":"the outside wall (die Wand = inside)"},
      {"f":"das Seil → die Seile","b":"the rope","ex":"Er balanciert auf dem Seil."},
      {"f":"die Kerze → die Kerzen","b":"the candle"},
      {"f":"der Mond → die Monde","b":"the moon"},
      {"f":"der Hut → die Hüte","b":"hat → hats"},
      {"f":"kaputt ⇄ ganz","b":"broken ⇄ whole / in one piece"},
      {"f":"kaputtgehen","b":"to break (by itself)","ex":"damit er nicht kaputt geht"},
      {"f":"ein hart gekochtes Ei","b":"a hard-boiled egg (participle as adjective)"},
      {"f":"damit","b":"so that (→ verb LAST, like weil)"},
      {"f":"balancieren","b":"to balance"},
      {"f":"sich verbeugen","b":"to bow"},
      {"f":"bequem","b":"comfortable","ex":"ein bequemer Stuhl"},
      {"f":"Hier ist / Hier sitzt …","b":"Here is / Here sits… — the describing frame"}
    ]
  },
  "esgibt": {
    deck: "DE · Es gibt",
    cards: [
      {"f":"Es gibt …","b":"There is / There are — ONE form for both (+ Akkusativ)"},
      {"f":"Es gibt einen Fluss.","b":"There is a river (der → einen: accusative)"},
      {"f":"Es gibt keine Palmen.","b":"There are no palm trees (negate with kein)"},
      {"f":"Gibt es …?","b":"Is there / are there …? (verb first)"},
      {"f":"es gibt ⇄ haben","b":"existence in general ⇄ a specific thing possesses it"},
      {"f":"das Bundesland → die Bundesländer","b":"federal state — Germany has 16"},
      {"f":"die Großstadt → die Großstädte","b":"large city — Germany has 81"},
      {"f":"die Insel → die Inseln","b":"island — 92, but only 19 inhabited"},
      {"f":"bewohnt ⇄ unbewohnt","b":"inhabited ⇄ uninhabited"},
      {"f":"der Fluss → die Flüsse","b":"river — about 15,000 in Germany"},
      {"f":"der Rhein","b":"the Rhine — Germany's longest river"},
      {"f":"die Palme → die Palmen","b":"the palm tree","ex":"In Deutschland gibt es keine Palmen."},
      {"f":"der Dialekt → die Dialekte","b":"dialect — Germany has ~20"},
      {"f":"Bayerisch / Hessisch / Plattdeutsch","b":"three German dialects"},
      {"f":"die Partei → die Parteien","b":"political party — 7 in the Bundestag"},
      {"f":"der Bundestag","b":"the German parliament, in Berlin"},
      {"f":"das Volksfest → die Volksfeste","b":"public festival — ~9,800 a year"},
      {"f":"das Oktoberfest","b":"the most famous Volksfest"},
      {"f":"der Weihnachtsmarkt → die Weihnachtsmärkte","b":"Christmas market — ~3,000"},
      {"f":"die Biersorte → die Biersorten","b":"kind of beer — ~5,000 in Germany"},
      {"f":"fließen","b":"to flow","ex":"Flüsse, die durch Deutschland fließen"},
      {"f":"ungefähr","b":"approximately"},
      {"f":"verschieden","b":"different / various"}
    ]
  }
};
