// Behavioural contract for the sync backend — the executable spec that made the AWS -> Cloudflare
// migration safe. Every case here was first validated against the REAL AWS Lambda code (running
// locally against an in-memory S3), so it documents what the backend actually did, not what it
// was assumed to do. The Cloudflare Worker then had to pass the identical 24 cases.
//
// Run against any backend:
//   PW_MOHAMED=<pw> PW_MUSTAFA=<pw> node tools/test_sync_contract.mjs http://localhost:8788
//
// The runner POSTs /__reset before each case, which the Worker only honours when ALLOW_RESET=1
// (never set in production). Against a backend without that hook, cases are order-dependent.

export const CASES = [
  { name: 'login: correct password returns a token + admin flag',
    steps: [{ a:{action:'login',user:'mohamed',pass:'PW'}, expect:r=>r.ok===true&&!!r.token&&r.admin===true }] },
  { name: 'login: wrong password is rejected 401',
    steps: [{ a:{action:'login',user:'mohamed',pass:'nope'}, expect:(r,s)=>s===401&&r.ok===false }] },
  { name: 'login: non-admin gets admin:false',
    steps: [{ a:{action:'login',user:'mustafa',pass:'PW2'}, expect:r=>r.ok===true&&r.admin===false }] },
  { name: 'pull: bad token is rejected 401',
    steps: [{ a:{action:'pull',user:'mohamed',token:'bogus',cursor:0}, expect:(r,s)=>s===401 }] },
  { name: 'push: sets done, pull sees it',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'1'}}}, auth:1,
              expect:r=>r.ok===true&&r.state['de.tea.done'].v==='1' }] },
  { name: 'push: done is PERMANENT — a bare "0" cannot un-done',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'1'}}}, auth:1 },
            { a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'0'}}}, auth:1,
              expect:r=>r.state['de.tea.done'].v==='1' }] },
  { name: 'push: {clear:true} DOES un-done and stamps cleared',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'1'}}}, auth:1 },
            { a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'0',clear:true}}}, auth:1,
              expect:r=>r.state['de.tea.done'].v==='0'&&r.state['de.tea.done'].cleared===true }] },
  { name: 'anki: per-card forward-only union (max wins)',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.anki':{v:{a:3,b:1}}}}, auth:1 },
            { a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.anki':{v:{a:1,b:5}}}}, auth:1,
              expect:r=>r.state['de.tea.anki'].v.a===3&&r.state['de.tea.anki'].v.b===5 }] },
  { name: 'anki: {reset:true} replaces the map',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.anki':{v:{a:3,b:9}}}}, auth:1 },
            { a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.anki':{v:{z:1},reset:true}}}, auth:1,
              expect:r=>r.state['de.tea.anki'].v.z===1&&r.state['de.tea.anki'].v.a===undefined }] },
  { name: 'cursor: a delta returns only entries newer than the cursor',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'1'}}}, auth:1, save:'seq' },
            { a:{action:'pull',user:'mohamed',cursor:'@seq'}, auth:1,
              expect:r=>Object.keys(r.state).length===0 }] },
  { name: 'cursor: 0 returns the WHOLE blob (cold client self-heal)',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'1'},'de.kitchen.done':{v:'1'}}}, auth:1 },
            { a:{action:'pull',user:'mohamed',cursor:0}, auth:1,
              expect:r=>!!r.state['de.tea.done']&&!!r.state['de.kitchen.done'] }] },
  { name: 'seq is monotonic across pushes',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.a.done':{v:'1'}}}, auth:1, save:'s1' },
            { a:{action:'push',user:'mohamed',cursor:0,changes:{'de.b.done':{v:'1'}}}, auth:1,
              expect:(r,s,saved)=>r.seq>saved.s1 }] },
  { name: 'idempotent: re-pushing the same done does not bump seq',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'1'}}}, auth:1, save:'s1' },
            { a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'1'}}}, auth:1,
              expect:(r,s,saved)=>r.seq===saved.s1 }] },
  { name: 'users are isolated: mustafa cannot see mohamed data',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.secret.done':{v:'1'}}}, auth:1 },
            { a:{action:'pull',user:'mustafa',cursor:0}, auth:2,
              expect:r=>r.state['de.secret.done']===undefined }] },
  { name: 'adminGet: non-admin gets 403',
    steps: [{ a:{action:'adminGet',user:'mustafa'}, auth:2, expect:(r,s)=>s===403 }] },
  { name: 'adminGet: admin sees every user blob',
    steps: [{ a:{action:'adminGet',user:'mohamed'}, auth:1,
              expect:r=>r.ok===true&&!!r.users.mohamed&&!!r.users.mustafa&&!!r.config }] },
  { name: 'adminSet: hiding a lesson shows up in that user pull',
    steps: [{ a:{action:'adminSet',user:'mohamed',config:{hidden:{mustafa:{koerper:true}}}}, auth:1 },
            { a:{action:'pull',user:'mustafa',cursor:0}, auth:2,
              expect:r=>r.hidden.includes('koerper') }] },
  { name: 'adminSet: the admin can never be hidden from himself',
    steps: [{ a:{action:'adminSet',user:'mohamed',config:{hidden:{mohamed:{tea:true}}}}, auth:1 },
            { a:{action:'pull',user:'mohamed',cursor:0}, auth:1,
              expect:r=>r.hidden.length===0 }] },
  { name: 'adminSet: forcing done for another user works',
    steps: [{ a:{action:'adminSet',user:'mohamed',progress:{mustafa:{'de.tea.done':'1'}}}, auth:1 },
            { a:{action:'pull',user:'mustafa',cursor:0}, auth:2,
              expect:r=>r.state['de.tea.done'].v==='1' }] },
  { name: 'adminSet: returns the CALLER own fresh full state',
    steps: [{ a:{action:'push',user:'mohamed',cursor:0,changes:{'de.tea.done':{v:'1'}}}, auth:1 },
            { a:{action:'adminSet',user:'mohamed',config:{hidden:{}}}, auth:1,
              expect:r=>r.ok===true&&!!r.state&&r.state['de.tea.done'].v==='1'&&typeof r.seq==='number' }] },
  { name: 'unknown action is a 400',
    steps: [{ a:{action:'nonsense',user:'mohamed'}, auth:1, expect:(r,s)=>s===400 }] },
  { name: 'CORS preflight (OPTIONS) is allowed',
    steps: [{ method:'OPTIONS', a:{}, expect:(r,s,sv,h)=>s===200&&!!h['access-control-allow-origin'] }] },
  { name: 'CORS headers present on a normal POST',
    steps: [{ a:{action:'login',user:'mohamed',pass:'PW'}, expect:(r,s,sv,h)=>!!h['access-control-allow-origin'] }] },
  { name: 'malformed JSON body is a 400',
    steps: [{ raw:'{not json', expect:(r,s)=>s===400 }] },
];
